@startuml
start
:User keys in help command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command specified])
    if () then ([command is valid])
        :Display command specific help message;
        stop
    else ([[command is invalid])
        :Display command does not exist message
        with general help message;
        stop
    endif
else ([command not specified])
    :Help window displays general help
    message;
    stop
endif
@enduml
