@startuml AddPatientSequenceDiagram
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":VmsParser" as VmsParser LOGIC_COLOR
participant ":PatientParser" as PatientParser LOGIC_COLOR
participant "a:AddCommandParser" as AddCommandParser LOGIC_COLOR
participant "a:AddCommand" as AddCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute("patient add \n˗˗n John Doe \n˗˗p 98765432 \n˗˗d 2001-03-19 \n˗˗b B+ \n˗˗a catfur, pollen \n˗˗v covax")
activate LogicManager

LogicManager -> VmsParser : parseCommand("patient add \n˗˗n John Doe \n˗˗p 98765432 \n˗˗d 2001-03-19 \n˗˗b B+ \n˗˗a catfur, pollen \n˗˗v covax")
activate VmsParser

VmsParser -> PatientParser : parse("add \n˗˗n John Doe \n˗˗p 98765432 \n˗˗d 2001-03-19 \n˗˗b B+ \n˗˗a catfur, pollen \n˗˗v covax")
activate PatientParser

create AddCommandParser
PatientParser -> AddCommandParser : parse("˗˗n John Doe \n˗˗p 98765432 \n˗˗d 2001-03-19 \n˗˗b B+ \n˗˗a catfur, pollen \n˗˗v covax")
activate AddCommandParser

create AddCommand
AddCommandParser -> AddCommand
activate AddCommand

AddCommand --> AddCommandParser
deactivate AddCommand

AddCommandParser --> PatientParser : a
deactivate AddCommandParser
AddCommandParser -[hidden]-> PatientParser : a
destroy AddCommandParser

PatientParser --> VmsParser : a
deactivate PatientParser

VmsParser --> LogicManager : a
deactivate VmsParser

LogicManager -> AddCommand : execute()
activate AddCommand

AddCommand -> Model : addPatient()
activate Model


Model --> AddCommand
deactivate Model

AddCommand --> LogicManager : result
deactivate AddCommand
AddCommand -[hidden]-> LogicManager : result
destroy AddCommand

[<--LogicManager
deactivate LogicManager
@enduml
