package seedu.task.logic.commands;

import seedu.task.logic.commands.exceptions.CommandException;
import seedu.task.model.Model;
import seedu.task.model.task.Date;

/**
 * Gets schedule for a date specified by user (limited to 30 days from when schedule was created)
 * Schedule is generated by the plan command (only when initiated by users).
 */
public class ScheduleCommand extends Command {
    public static final String COMMAND_WORD = "schedule";

    public static final String MESSAGE_USAGE = COMMAND_WORD + ": returns a day's work plan.\n"
            + "Example: " + COMMAND_WORD + " 2023-04-26 0000";

    public static final String SCHEDULE_SUCCESS_MESSAGE = "Daily Plan Displayed";

    private final Date date;
    public ScheduleCommand(Date date) {
        this.date = date;
    }

    @Override
    public CommandResult execute(Model model) throws CommandException {
        model.schedule(date);
        return new CommandResult(SCHEDULE_SUCCESS_MESSAGE);
    }

    @Override
    public boolean equals(Object other) {
        return other == this // short circuit if same object
                || (other instanceof ScheduleCommand // instanceof handles nulls
                && (date.equals(((ScheduleCommand) other).date))); // state check
    }
}
