
@startuml
!pragma useVerticalIf on
start
:User enters aetd command;
if () then ([else])
  :Error: Invalid command format;
  stop
([Command format is valid])elseif () then ([else])
  :Error: Employee does not exist in SudoHR;
  stop
([Employee exists in SudoHR])elseif () then ([else])
 :Error: Department does not exist in SudoHR;
  stop
([Department exists in SudoHR])elseif () then ([else])
  :Error: Employee already exists in the department;
  stop
 else ([Employee does not exist in the department])
  :aetd command successfully executes.;
stop

@enduml
