
@startuml
!pragma useVerticalIf on
start
:User enters refd command;
if () then ([else])
  :Error: Invalid command format;
  stop
([Command format is valid])elseif () then ([else])
  :Error: Employee does not exist in SudoHR;
  stop
([Employee exists in SudoHR])elseif () then ([else])
 :Error: Department does not exist in SudoHR;
  stop
([Department exists in SudoHR])elseif () then ([else])
  :Error: Employee not found in the department;
  stop
 else ([Employee found in the department])
  :refd command successfully executes.;
stop

@enduml
