@startuml
'https://plantuml.com/activity-diagram-beta

start
:User requests to find a person called Thomas of age 14;

if () then ([name and age exists])
    :Finds cases associated with said name and age;
    :Displays how many cases was found with name and age;
    stop
else ([else])
    :Displays an empty case list;
    stop
endif

@enduml
