@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":DengueHotspotTrackerParser" as DengueHotspotTrackerParser LOGIC_COLOR
participant ":FindCommandParser" as FindCommandParser LOGIC_COLOR
participant "p:FindPredicate" as FindPredicate LOGIC_COLOR
participant "f:FindCommand" as FindCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("find n/Aeron")
activate LogicManager

LogicManager -> DengueHotspotTrackerParser : parseCommand("find n/Aeron")
activate DengueHotspotTrackerParser

create FindCommandParser
DengueHotspotTrackerParser -> FindCommandParser
activate FindCommandParser

FindCommandParser --> DengueHotspotTrackerParser
deactivate FindCommandParser

DengueHotspotTrackerParser -> FindCommandParser : parse("n/Aeron")
activate FindCommandParser


create FindPredicate
FindCommandParser -> FindPredicate
activate FindPredicate

FindPredicate  --> FindCommandParser : p
deactivate FindPredicate

create FindCommand
FindCommandParser -> FindCommand : FindCommand(p)
activate FindCommand

FindCommand --> FindCommandParser : f
deactivate FindCommand

FindCommandParser --> DengueHotspotTrackerParser : f
deactivate FindCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindCommandParser -[hidden]-> DengueHotspotTrackerParser

DengueHotspotTrackerParser --> LogicManager : f
deactivate DengueHotspotTrackerParser

LogicManager -> FindCommand : execute()
activate FindCommand

FindCommand -> Model : updateFilteredPersonList(p)
activate Model

Model --> FindCommand
deactivate Model

create CommandResult
FindCommand -> CommandResult
activate CommandResult

CommandResult --> FindCommand
deactivate CommandResult

FindCommand --> LogicManager : result
deactivate FindCommand

[<--LogicManager
deactivate LogicManager
@enduml
