@startuml
!include ../../style.puml

mainframe sd Switch tabs
participant ":SwitchKey" as SwitchKey MODEL_COLOR
participant "mainWindow:MainWindow" as MainWindow LOGIC_COLOR
participant "entityPanel:EntityPanel" as EntityPanel

activate SwitchKey
SwitchKey -> MainWindow : nextTab()
activate MainWindow
MainWindow -> EntityPanel : nextTab()
activate EntityPanel
EntityPanel -> EntityPanel : Switches to next tab
EntityPanel --> MainWindow
deactivate EntityPanel
MainWindow --> SwitchKey
deactivate MainWindow
@enduml

