@startuml
!pragma useVerticalIf on
start
:User enters del command;
if () then ([else])
  :Error: Invalid command format;

([Command format is valid])elseif () then ([else])
  :Error: Employee to delete from SudoHR is not found;

else ([Employee exists in SudoHR])
  :del command successfully executes;

endif
stop

@enduml
