package seedu.internship.model.internship;

import static java.util.Objects.requireNonNull;

/**
 * Represents an Internship's Id in the internship catalogue.
 * Guarantees: immutable
 */
public class Id {

    public final String id;

    /**
     * Constructs a {@code Id}.
     *
     * @param Id A valid String id generated by TinS.
     */
    public Id(String Id) {
        requireNonNull(Id);
        this.id = Id;
    }

    @Override
    public String toString() {
        return this.id;
    }

    @Override
    public boolean equals(Object other) {
        return other == this // short circuit if same object
                || (other instanceof Id // instanceof handles nulls
                && id.equals(((Id) other).id)); // state check
    }

    @Override
    public int hashCode() {
        return id.hashCode();
    }

}
