@startuml
mainframe sd Show help
participant ":HelpKey" as HelpKey
participant "mainWindow:MainWindow" as MainWindow
participant "helpWindow:HelpWindow" as HelpWindow

activate HelpKey
HelpKey -> MainWindow : handleHelp()
activate MainWindow
alt helpWindow is showing
    MainWindow -> HelpWindow : show()
    HelpWindow --> MainWindow
else
    MainWindow -> HelpWindow : focus()
    HelpWindow --> MainWindow
end

MainWindow --> HelpKey
@enduml

