@startuml
sprite $rake [16x16/8] {
0000000000000000
0000000jj0000000
0000000jj0000000
0005555jj5555000
000jjeejjeejj000
000jj00jj00jj000
000jj00jj00jj000
0000000000000000
}
start
:User enters add command input;
:AddCommandParser parses input <$rake>;

if () then ([Parser returns AddCommand])
    :Execute add command;
    :Add person to TeamBuilder;
    :Person stored in storage;
    :PersonCard of newly added person displayed in Ui;
else ([Parser throws exception])])
    :Display error message;
endif
stop
@enduml
