@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":InternshipBookParser" as InternshipBookParser LOGIC_COLOR
participant ":AddApplicationCommandParser" as AddApplicationCommandParser LOGIC_COLOR
participant "d:AddApplicationCommand" as AddApplicationCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":Application" as Application MODEL_COLOR
end box

note left of LogicManager #aqua
Let user input be <str>
str = "r/SWE c/Google
e/googlehires@gmail.com s/applied"
end note

[-> LogicManager : execute("add {str}")
activate LogicManager

LogicManager -> InternshipBookParser : parseCommand("add {str}")
activate InternshipBookParser

create AddApplicationCommandParser
InternshipBookParser -> AddApplicationCommandParser
activate AddApplicationCommandParser

AddApplicationCommandParser --> InternshipBookParser
deactivate AddApplicationCommandParser

InternshipBookParser -> AddApplicationCommandParser : parse("{str}")
activate AddApplicationCommandParser

create Application
AddApplicationCommandParser -> Application
activate Application

Application --> AddApplicationCommandParser : app
deactivate Application

create AddApplicationCommand
AddApplicationCommandParser -> AddApplicationCommand : new AddApplicationCommand(app)
activate AddApplicationCommand

AddApplicationCommand --> AddApplicationCommandParser : addCommand
deactivate AddApplicationCommand

AddApplicationCommandParser --> InternshipBookParser : addCommand
deactivate AddApplicationCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddApplicationCommandParser -[hidden]-> InternshipBookParser
destroy AddApplicationCommandParser

InternshipBookParser --> LogicManager : addCommand
deactivate InternshipBookParser

LogicManager -> AddApplicationCommand : execute()
activate AddApplicationCommand

AddApplicationCommand -> Model : addApplication(app)
activate ApplicationModel

Model --> AddApplicationCommand
deactivate Model

create CommandResult
AddApplicationCommand -> CommandResult
activate CommandResult

CommandResult --> AddApplicationCommand
deactivate CommandResult

AddApplicationCommand --> LogicManager : result
deactivate AddApplicationCommand

[<--LogicManager
deactivate LogicManager

@enduml

