@startuml
start
:User enters command add_contact;
if () then ([PREFIX p/ and e/ are present])
    :Parse command arguments;
    if () then ([Phone number and email are valid])
            :Generate new AddContactCommand;
            if () then ([Provided index is valid])
                    :Add contact details to the specified application;
                    :Generate success message;
                else ([else])
                :Generate error message;
                endif
        else ([else])
        :Generate error message;
        endif
    else ([else])
    :Generate error message;
endif
:Display result message to user;
stop
@enduml
