@startuml
start
:User enters command add_contact;
if () then ([PREFIX p/ and e/ is present])
    :Parse command arguments;
    if () then ([Provided index is valid])
        if () then ([Phone number is valid])
            if () then ([Email address is valid])
            :Generate new AddContactCommand;
            :Add contact details to specified internship;
            :Generate success message;
                else ([else])
                :Generate error message;
                endif
            else ([else])
            :Generate error message;
            endif
        else ([else])
        :Generate error message;
        endif
    else ([else])
    :Generate error message;
endif
:Display result message to user;
stop
@enduml
