@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MasterDeckParser" as MasterDeckParser LOGIC_COLOR
participant ":AddDeckCommandParser" as AddDeckCommandParser LOGIC_COLOR
participant "u:AddDeckCommand" as AddDeckCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":MasterDeck" as MasterDeck MODEL_COLOR
end box

[-> LogicManager : execute("addDeck Math")
activate LogicManager

LogicManager -> Model : getState()
activate Model
Model --> LogicManager : state
deactivate Model
alt Main_Unselected_Mode
    LogicManager -> MasterDeckParser : parseCommand("addDeck Math")
    activate MasterDeckParser
    create AddDeckCommandParser
    MasterDeckParser -> AddDeckCommandParser
    activate AddDeckCommandParser

    AddDeckCommandParser --> MasterDeckParser
    deactivate AddDeckCommandParser

    MasterDeckParser -> AddDeckCommandParser : parse("Math")
    activate AddDeckCommandParser

    create AddDeckCommand
    AddDeckCommandParser -> AddDeckCommand
    activate AddDeckCommand

    AddDeckCommand --> AddDeckCommandParser : u
    deactivate AddDeckCommand

    AddDeckCommandParser --> MasterDeckParser : u
    deactivate AddDeckCommandParser

    AddDeckCommandParser -[hidden]-> MasterDeckParser
    destroy AddDeckCommandParser
    MasterDeckParser --> LogicManager : u
    deactivate MasterDeckParser

    LogicManager -> AddDeckCommand : execute()
    activate AddDeckCommand

    AddDeckCommand -> Model : addDeck(Math)
    activate Model

    Model --> MasterDeck : addDeck(Math)
    activate MasterDeck
    MasterDeck --> Model :
    deactivate MasterDeck
    Model --> AddDeckCommand
    deactivate Model

    create CommandResult
    AddDeckCommand -> CommandResult
    activate CommandResult

    CommandResult --> AddDeckCommand
    deactivate CommandResult

    AddDeckCommand --> LogicManager : result
    deactivate AddDeckCommand

else else
    LogicManager -> MasterDeckParser : parseCommand("addDeck Math")
    activate MasterDeckParser
    MasterDeckParser --> LogicManager : ParseException
    deactivate MasterDeckParser

end
[<--LogicManager
deactivate LogicManager
@enduml
