@startuml
start
:User enters command add_docs;
if () then ([PREFIX rs/ and cl/ are present])
    :Parse command arguments;
    if () then ([Resume and cover letter links are valid])
            :Generate new AddDocumentsCommand;
            if () then ([Provided index is valid])
                    :Add document links to the specified application;
                    :Generate success message;
                else ([else])
                :Generate error message;
                endif
        else ([else])
        :Generate error message;
        endif
    else ([else])
    :Generate error message;
endif
:Display result message to user;
stop
@enduml
