@startuml

start
:User inputs 'addDeck DECK_NAME' command;


if () then ([Deck name already exists])
    :PowerCard throws
    DuplicateDeckException;
else ([else])
    :PowerCard creates new deck;

endif

stop
@enduml
