@startuml

start
:User is in MAIN_UNSELECTED_MODE;
:User inputs 'addDeck DECK_NAME';

if () then ([Deck name already exists])
    :PowerCard throws
    DuplicateDeckException;
else ([else])
    :PowerCard creates and
    displays new deck;

endif

stop
@enduml
