@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic {

Class FitBookParser
Class AddCommand
Class CommandResult
Class "{abstract}\nCommand" as Command


Class "<<interface>>\nLogic" as Logic
Class LogicManager
}

package FitBookModel{
Class HiddenFitBookModel #FFFFFF
}

package Storage{
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .right.|> Logic
LogicManager -right->"1" FitBookParser
FitBookParser ..> AddCommand : creates >

AddCommand -up-|> Command
LogicManager .left.> Command : executes >

LogicManager --> FitBookModel : adds the new client >
LogicManager --> Storage : stores the new client >
Storage --[hidden] FitBookModel
Command .[hidden]up.> Storage
Command .right.> FitBookModel

Logic ..> CommandResult
LogicManager .down.> CommandResult
Command .up.> CommandResult : produces >
@enduml
