@startuml
!include style.puml
skinparam DefaultFontSize 50

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddEventCommandParser" as AddEventCommandParser LOGIC_COLOR
participant "a:AddEventCommand" as AddEventCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":AddressBook" as AddressBook MODEL_COLOR
participant "e:Event" as Event MODEL_COLOR
end box

[-> LogicManager : execute("addevent\n ev/Carnival\n from/17-07-2023 12:00\n to/23-07-2023 22:00")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("addevent\n ev/Carnival\n from/17-07-2023 12:00\n to/23-07-2023 22:00")
activate AddressBookParser

create AddEventCommandParser
AddressBookParser -> AddEventCommandParser
activate AddEventCommandParser

AddEventCommandParser --> AddressBookParser
deactivate AddEventCommandParser

AddressBookParser -> AddEventCommandParser : parse("ev/Carnival from/17-07-2023\n12:00 to/23-07-2023 22:00")
activate AddEventCommandParser

create Event
AddEventCommandParser -> Event
activate Event
Event --> AddEventCommandParser : e
deactivate Event

create AddEventCommand
AddEventCommandParser -> AddEventCommand : AddEventCommand(e)
activate AddEventCommand

AddEventCommand --> AddEventCommandParser : a
deactivate AddEventCommand

AddEventCommandParser --> AddressBookParser : a
deactivate AddEventCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddEventCommandParser -[hidden]-> AddressBookParser
destroy AddEventCommandParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> AddEventCommand : execute(model)
activate AddEventCommand

AddEventCommand -> Model : hasEvent(e)
activate Model
Model --> AddEventCommand
deactivate Model

AddEventCommand -> Model : addEvent(e)
activate Model
Model -> AddressBook : addEvent(e)
activate AddressBook

AddressBook --> Model
deactivate AddressBook

Model -> Model : update event list to show all events

Model --> AddEventCommand
deactivate Model

create CommandResult
AddEventCommand -> CommandResult
activate CommandResult

CommandResult --> AddEventCommand
deactivate CommandResult

AddEventCommand --> LogicManager : result
deactivate AddEventCommand

[<--LogicManager
deactivate LogicManager
@enduml
