@startuml
!include style.puml

box Logic #C8C8FA
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddMeetingCommandParser" as AddMeetingCommandParser LOGIC_COLOR
participant ":AddMeetingCommand" as AddMeetingCommand LOGIC_COLOR
end box

[-> LogicManager : execute(meetingAdd 1 \n "md/Meeting with Alex ms/30-04-2023 23:30 \n me/30-04-2023 23:40")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(meetingAdd 1 \n"md/Meeting with Alex ms/30-04-2023 23:30 \n me/30-04-2023 23:40")
activate AddressBookParser

create AddMeetingCommandParser
AddressBookParser -> AddMeetingCommandParser : parse("md/Meeting with Alex  ms/30-04-2023 23:30  me/30-04-2023 23:40")
activate AddMeetingCommandParser

create AddMeetingCommand
AddMeetingCommandParser -> AddMeetingCommand : AddMeetingCommand(desc, index, meeting)
activate AddMeetingCommand

AddMeetingCommand --> AddMeetingCommandParser
deactivate AddMeetingCommand

AddMeetingCommandParser --> AddressBookParser
deactivate AddMeetingCommandParser

AddressBookParser --> LogicManager
deactivate AddressBookParser

LogicManager -> AddMeetingCommand : execute(model)
activate AddMeetingCommand

[<-- LogicManager
deactivate LogicManager
@enduml
