@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddPatientCommandParser" as AddPatientCommandParser LOGIC_COLOR
participant "a:AddPatientCommand" as AddPatientCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("add-ptn n/John Doe p/98765432 e/jdoe@gmail.com h/1.85 w/70.5 d/Fever st/Outpatient r/Patient was given paracetamol for fever t/friends")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("add-ptn n/John Doe p/98765432 e/jdoe@gmail.com h/1.85 w/70.5 d/Fever st/Outpatient r/Patient was given paracetamol for fever t/friends")
activate AddressBookParser

create AddPatientCommandParser
AddressBookParser -> AddPatientCommandParser
activate AddPatientCommandParser

AddPatientCommandParser --> AddressBookParser
deactivate AddPatientCommandParser

AddressBookParser -> AddPatientCommandParser : parse("n/John Doe p/98765432 e/jdoe@gmail.com h/1.85 w/70.5 d/Fever st/Outpatient r/Patient was given paracetamol for fever t/friends")
activate AddPatientCommandParser

create AddPatientCommand
AddPatientCommandParser -> AddPatientCommand
activate AddPatientCommand

AddPatientCommand --> AddPatientCommandParser : a
deactivate AddPatientCommand

AddPatientCommandParser --> AddressBookParser : a
deactivate AddPatientCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddPatientCommandParser -[hidden]-> AddressBookParser
destroy AddPatientCommandParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> AddPatientCommand : execute()
activate AddPatientCommand

AddPatientCommand -> Model : addPatient(patient)
activate Model

Model --> AddPatientCommand
deactivate Model

create CommandResult
AddPatientCommand -> CommandResult
activate CommandResult

CommandResult --> AddPatientCommand
deactivate CommandResult

AddPatientCommand --> LogicManager : result
deactivate AddPatientCommand

[<--LogicManager
deactivate LogicManager
@enduml
