@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class AddressBook
Class ModelManager

Class UniqueClientList
Class Client
Class Name
Class Phone
Class Email
Class UniqueProjectList
Class Tag

AddressBook *--> "1" UniqueClientList
UniqueClientList --> "*" Client : all

ModelManager -->"*" Client : filtered
ModelManager -->"*" Client : sorted

Client *--> "1" Name
Client *--> "0..1" Phone
Client *--> "0..1" Email
Client *--> "1" UniqueProjectList
Client *--> "*" Tag

@enduml
