@startuml
!include style.puml

box sd Create Module
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant "<<class>>\nParserUtil" as ParserUtil LOGIC_COLOR
participant "code:ModuleCode" as ModuleCode LOGIC_COLOR
participant "name:ModuleName" as ModuleName LOGIC_COLOR
participant "m:Module" as Module LOGIC_COLOR
end box

activate AddCommandParser

AddCommandParser -> ParserUtil : parseModuleCode("CS2040S")
activate ParserUtil

create ModuleCode
ParserUtil -> ModuleCode : ModuleCode("CS2040S")
activate ModuleCode

ModuleCode --> ParserUtil
deactivate ModuleCode

ParserUtil --> AddCommandParser : code
deactivate ParserUtil

AddCommandParser -> ParserUtil : parseModuleName("")
activate ParserUtil

create ModuleName
ParserUtil -> ModuleName : ModuleName("")
activate ModuleName

ModuleName --> ParserUtil
deactivate ModuleName

ParserUtil --> AddCommandParser : name
deactivate ParserUtil

create Module
AddCommandParser -> Module : Module(code, name, emptytagset, emptylecturelist)
activate Module

Module --> AddCommandParser
deactivate Module

AddCommandParser -[hidden]-> AddCommandParser
deactivate AddCommandParser

@enduml
