@startuml
'https://plantuml.com/class-diagram
!include style.puml

package logic {

package commands {
Class "{abstract}\nCommand" as Command #9AEA54
Class AddTodoCommand #61B417 extends Command
}

package parser {
Class "<<interface>>\nParser" as Parser #18F2D8
Class AddTodoCommandParser #15B4A1 implements Parser

}

@enduml
