@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":InternshipBookParser" as InternshipBookParser LOGIC_COLOR
participant ":AddTaskCommandParser" as AddTaskCommandParser LOGIC_COLOR
participant ":EditApplicationDescriptor" as EditApplicationDescriptor LOGIC_COLOR
participant ":AddTaskCommand" as AddTaskCommand LOGIC_COLOR
participant ":EditApplicationCommand" as EditApplicationCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

note left of LogicManager #aqua
Let user input be: <str>
str = "d/Interview by/30-12-2023"
end note

[-> LogicManager : execute("add-task 1 {str}")

LogicManager -> InternshipBookParser : parseCommand("add-task 1 {str}")

create AddTaskCommandParser
InternshipBookParser -> AddTaskCommandParser

AddTaskCommandParser --> InternshipBookParser

InternshipBookParser -> AddTaskCommandParser : parse("1 {str}")
activate AddTaskCommandParser

create EditApplicationDescriptor
AddTaskCommandParser -> EditApplicationDescriptor
activate EditApplicationDescriptor

EditApplicationDescriptor --> AddTaskCommandParser : d
deactivate EditApplicationDescriptor

create AddTaskCommand
AddTaskCommandParser -> AddTaskCommand
activate AddTaskCommand

AddTaskCommand --> AddTaskCommandParser : addTaskCommand
deactivate AddTaskCommand

AddTaskCommandParser --> InternshipBookParser : addTaskCommand
deactivate AddTaskCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddTaskCommandParser -[hidden]-> InternshipBookParser
destroy AddTaskCommandParser

InternshipBookParser --> LogicManager : addTaskCommand
deactivate InternshipBookParser

LogicManager -> AddTaskCommand : execute()
activate AddTaskCommand

AddTaskCommand -> EditApplicationCommand : createEditedApplication()

AddTaskCommand -> Model : setApplication()


create CommandResult
AddTaskCommand -> CommandResult
activate CommandResult

CommandResult --> AddTaskCommand
deactivate CommandResult

AddTaskCommand --> LogicManager : result
deactivate AddTaskCommand

[<--LogicManager
deactivate LogicManager
@enduml
