@startuml
start
:User uses alert command;
'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if ()  then ([input is empty])
     :Uses default 24hr alert window;
else([input includes timeframe])
    :Uses input timeframe as alert window;
endif

:alert command executed;
:model updates alert task filtered list;
:Update UI to show user alert list;
stop
@enduml
