@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class UI UI_COLOR
    Class Logic LOGIC_COLOR
    Class Storage STORAGE_COLOR
    Class Model MODEL_COLOR
    Class Main MAIN_COLOR
    Class Commons COMMONS_COLOR
}

Class "<$user>" as User USER_COLOR
Class "<$documents>" as File IMG_COLOR


UI -[UI_COLOR]left-> Logic
UI -[UI_COLOR]right-> Model
Logic -[LOGIC_COLOR]right-> Storage
Logic -[LOGIC_COLOR]-> Model
Main -[MAIN_COLOR]-> UI
Main -[MAIN_COLOR]up-> Logic
Main -[MAIN_COLOR]-> Storage
Main -[MAIN_COLOR]left-> Model
Main -[hidden]-> Commons
Logic -[hidden]-> Storage

Storage -[STORAGE_COLOR].> Model
Storage .[STORAGE_COLOR]left.> File
User ..> UI
@enduml
