@startuml
| User |
start
:User executes archive command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

| System |
if () then ([pet entry exists in the PetPal list])
    :System saves pet entry into
    archive list;
    :System deletes pet entry from
     PetPal list;
else ([else])
    : System displays error message;
endif

stop
@enduml
