@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class UI UI_COLOR
    Class CareFlowLogic LOGIC_COLOR
    Class CareFlowStorage STORAGE_COLOR
    Class CareFlowModel MODEL_COLOR
    Class Main #grey
    Class Commons LOGIC_COLOR_T2
}

Class "<$user>" as User MODEL_COLOR_T2
Class "<$documents>" as File UI_COLOR_T1


UI -[#green]> CareFlowLogic
UI -right[#green]-> CareFlowModel
CareFlowLogic -[#blue]-> CareFlowStorage
CareFlowLogic -down[#blue]-> CareFlowModel
Main -[#grey]-> UI
Main -[#grey]-> CareFlowLogic
Main -[#grey]-> CareFlowStorage
Main -up[#grey]-> CareFlowModel
Main -down[hidden]-> Commons

CareFlowStorage -up[STORAGE_COLOR].> CareFlowModel
CareFlowStorage .right[STORAGE_COLOR].>File
User ..> UI
@enduml
