@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class UI UI_COLOR
    Class Logic LOGIC_COLOR
    Class Storage STORAGE_COLOR
    Class Model MODEL_COLOR
    Class Main MAIN_COLOR
    Class Commons COMMONS_COLOR
}

Class "<$user>" as User USER_COLOR
Class "<$documents>" as File IMG_COLOR


UI -[UI_COLOR]> Logic
UI -right[UI_COLOR]-> Model
Logic -[LOGIC_COLOR]-> Storage
Logic -down[LOGIC_COLOR]-> Model
Main -[MAIN_COLOR]-> UI
Main -[MAIN_COLOR]-> Logic
Main -[MAIN_COLOR]-> Storage
Main -up[MAIN_COLOR]-> Model
Main -down[hidden]-> Commons

Storage -up[STORAGE_COLOR].> Model
Storage .right[STORAGE_COLOR].> File
User ..> UI
@enduml
