@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":PetPalParser" as PetPalParser LOGIC_COLOR
participant ":ArchiveCommandParser" as ArchiveCommandParser LOGIC_COLOR
participant "a:ArchiveCommand" as ArchiveCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("archive 1")
activate LogicManager

LogicManager -> PetPalParser : parseCommand("archive 1")
activate PetPalParser

create ArchiveCommandParser
PetPalParser -> ArchiveCommandParser
activate ArchiveCommandParser

ArchiveCommandParser --> PetPalParser
deactivate ArchiveCommandParser

PetPalParser -> ArchiveCommandParser : parse("1")
activate ArchiveCommandParser

create ArchiveCommand
ArchiveCommandParser -> ArchiveCommand
activate ArchiveCommand

ArchiveCommand --> ArchiveCommandParser : a
deactivate ArchiveCommand

ArchiveCommandParser --> PetPalParser : a
deactivate ArchiveCommandParser
'Hidden arrow to position to destroy marker below the end of the activation bar.
ArchiveCommandParser -[hidden]-> PetPalParser
destroy ArchiveCommandParser

PetPalParser --> LogicManager : a
deactivate PetPalParser

LogicManager -> ArchiveCommand : execute()
activate ArchiveCommand

ArchiveCommand -> Model : archivePet(1)
activate Model

Model --> ArchiveCommand
deactivate Model

create CommandResult
ArchiveCommand -> CommandResult
activate CommandResult

CommandResult --> ArchiveCommand
deactivate CommandResult

ArchiveCommand --> LogicManager : result
deactivate ArchiveCommand

[<--LogicManager
deactivate LogicManager
@enduml