@startuml
start
:Search for person(s) and task(s);
:Lists person(s) and task(s);
:User inputs chooses person and task by their indices;
if() then ([valid indices])
    :Assigns task to person;
else([else])
    :OfficeConnect throws an error;
endif
stop
@enduml
