@startuml
'https://plantuml.com/sequence-diagram

!include Style.puml
title BatchAddCommand

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ExecutiveProParser" as ExecutiveProParser LOGIC_COLOR
participant ":BatchAddCommandParser" as BatchAddCommandParser LOGIC_COLOR
participant "b:BatchAddCommand" as BatchAddCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

[-> LogicManager: execute("batchadd executivepro.csv")
activate LogicManager

LogicManager -> ExecutiveProParser: parseCommand("batchadd executivepro.csv")
activate ExecutiveProParser

create BatchAddCommandParser
ExecutiveProParser->BatchAddCommandParser
activate BatchAddCommandParser

BatchAddCommandParser --> ExecutiveProParser
deactivate BatchAddCommandParser

ExecutiveProParser -> BatchAddCommandParser : parse("executivepro.csv")
activate BatchAddCommandParser

create BatchAddCommand
BatchAddCommandParser -> BatchAddCommand : BatchAddCommand(executivepro.csv)
activate BatchAddCommand


BatchAddCommand --> BatchAddCommandParser : b
deactivate BatchAddCommand

BatchAddCommandParser --> ExecutiveProParser : b
deactivate BatchAddCommandParser

ExecutiveProParser --> LogicManager : b
deactivate ExecutiveProParser

LogicManager -> BatchAddCommand : execute(model)
activate BatchAddCommand

BatchAddCommand -> BatchAddCommand : getInfo()
activate BatchAddCommand
loop #white  rows  in  (CSV) file
    ref over BatchAddCommand
    AddCommandParser.parse(row)
    end
end
BatchAddCommand --> BatchAddCommand
deactivate BatchAddCommand
|||

loop #white AddCommands  in  list
ref over BatchAddCommand
AddCommand.execute(model)
end
end

create CommandResult
BatchAddCommand -> CommandResult
activate CommandResult

CommandResult --> BatchAddCommand
deactivate CommandResult

BatchAddCommand --> LogicManager
deactivate BatchAddCommand

@enduml
