@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Wife *-right-> "1" UniqueFoodList
Wife *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueFoodList
UniqueTagList -[hidden]down- UniqueFoodList

UniqueTagList *-right-> "0..50" Tag
Tag *-right-> "1" TagName

UniqueFoodList *-right-> Food
Food *-up-> "*" Tag


Food *--> "1" Name
Food *--> "1" Unit
Food *--> "1" Quantity
Food *--> "1" ExpiryDate
@enduml
