@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueRoleList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueRoleList
UniqueTagList -[hidden]down- UniqueRoleList

UniqueTagList -right-> "*" Tag
UniqueRoleList -right-> Role

Role -up-> "*" Tag

Role *--> Name
Role *--> Phone
Role *--> Email
Role *--> Address
@enduml
