@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>> {
Class MainWindow
Class HelpWindow
Class ExportProgressWindow
Class ExportWindow
Class ImportWindow
Class ResultDisplay
Class StudentListPanel
Class StudentCard
Class TaskListPanel
Class TaskCard
Class ScoreListPanel
Class ScoreCard
Class StatusBarFooter
Class CommandBox
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

MainWindow *-up-> "1" CommandBox
MainWindow *-up-> "1" ResultDisplay
MainWindow *-down-> "1" StudentListPanel
MainWindow *-down-> "1" TaskListPanel
MainWindow *-down-> "1" ScoreListPanel
MainWindow *-up-> "1" StatusBarFooter
MainWindow --> "0..1" HelpWindow
MainWindow -up-> "0..1" ExportProgressWindow
MainWindow -up-> "0..1" ExportWindow
MainWindow --> "0..1" ImportWindow

StudentListPanel -down-> "*" StudentCard
TaskListPanel -down-> "*" TaskCard
ScoreListPanel -down-> "*" ScoreCard

StudentCard ..> Model
TaskCard ..> Model
ScoreCard ..> Model

@enduml
