@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class "{abstract}\nEvent" as Event

AddressBook *-> "1" UniquePersonList
AddressBook *--> "1" UniqueTutorialList

UniquePersonList -right-> "*" Person
UniqueTutorialList -right-> "*" Tutorial

Tutorial -up-|> Event

Tutorial *--> "1" Name
Tutorial *--> "1" LocalDateTime
Tutorial --> "*" Note
Tutorial --> "*" Person

@enduml
