@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

ConnectUs *-right-> "1" UniquePersonList
ConnectUs *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniquePersonList

UniqueTagList -right-> "*" Remark
UniqueTagList -right-> "0..2" Major
UniqueTagList -right-> "*" CCA
UniqueTagList -right-> "*" Module
UniquePersonList -right-> Person

Person *-up-> "*" Module
Person *-up-> "*" CCA
Person *-up-> "0..2" Major
Person *-up-> "*" Remark

Person *--> "1" Name
Person *--> "0..1" Phone
Person *--> "0..1" Email
Person *--> "0..1" Address
@enduml
