@startuml
!include style.puml

box Ui UI_COLOR_T1
participant "{abstract}\nPage" as Page UI_COLOR
participant ":CalendarPage" as CalendarPage UI_COLOR
end box

box CalendarFX EXTERNAL_COLOR_T1
participant "monthPage:MonthPage" as MonthPage EXTERNAL_COLOR
participant "calendarSource:CalendarSource" as CalendarSource EXTERNAL_COLOR
participant "internshipEvents:Calendar" as Calendar EXTERNAL_COLOR
participant ":Entry" as Entry EXTERNAL_COLOR
end box

[-> Page : <<static>>\nPage.of(CommandResult)
activate Page

create CalendarPage
Page -> CalendarPage
activate CalendarPage

CalendarPage -> CalendarPage : initializeCalendar()
activate CalendarPage

create MonthPage
CalendarPage -> MonthPage

create Calendar
CalendarPage -> Calendar

create CalendarSource
CalendarPage -> CalendarSource

CalendarPage -> CalendarSource : calendarSource\n.getCalendar()\n.addAll(internshipEvents)
CalendarPage -> MonthPage : monthPage\n.getCalendarSources()\n.addAll(calendarSource)

|||
note over MonthPage : Not shown: \n Initializing calendar time \n Setting calendar style
|||

deactivate CalendarPage

CalendarPage -> CalendarPage : addCalendarEntries()
activate CalendarPage

loop for each Event in ObservableList<Event>
create Entry
CalendarPage -> Entry

CalendarPage -> Entry : setInterval(LocalDateTime)

opt Event is a deadline
CalendarPage -> Entry : setFullDay(true)

|||
end
|||
end

deactivate CalendarPage
|||
CalendarPage --> Page
deactivate CalendarPage


Page -->[ : CalendarPage
deactivate Page
@enduml