@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

show attributes
hide empty attributes

Client : name
Client : phone
Client : email
Client : UniqueProjectList projects
Client *-->"*" Tag
@enduml
