@startuml

start
:User enters command;

if (Checking validity of command in current application mode) then ([command is valid])
    :Execute command;
    :Display Command Result on Result Display;
else ([else])
    :Throw ParseException;
    :Display error message on Result Display;

endif

stop
@enduml
