@startuml
'https://plantuml.com/class-diagram
!include style.puml
skinparam arrowThickness 1.1

package Commitment MODEL_COLOR_BACKGROUND {
    class Commitment MODEL_COLOR
    class Lesson MODEL_COLOR
}

package Location MODEL_COLOR_BACKGROUND {
    class Location MODEL_COLOR
}

package Time MODEL_COLOR_BACKGROUND {
    class TimePeriod MODEL_COLOR
}

Lesson .[MODEL_COLOR]right.|> Commitment

Commitment .[MODEL_COLOR]right.> "1" Location
Commitment -[MODEL_COLOR]right-> "1" TimePeriod

Location -[hidden]-> TimePeriod

@enduml
