@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command commits TeamBuilder])
    :New Memento produced by Model;
    :Memento stored with context in HistoryUtil;
    :HistoryUtil purges redundant Mementos;
else ([else])
endif
stop
@enduml
