@startuml

start
:User enters command;

if (Checking validity of command in current application mode) then ([command is valid])
    :Store changes in MasterDeckStorage;
    :Save Command Result to Logic Manager;
    :Display Command Result on Result Display;
else ([else])
    :Throws ParseException;
    :Displays error message on Result Display;

endif

stop
@enduml
