@startuml
!include style.puml

package "Logic component" {
    Class "<<interface>>\nLogic" as Logic LOGIC_COLOR
    Class LogicManager LOGIC_COLOR
}

package "Model component" {
    Class DummyModel #FFFFFF
}

package "Storage component" {
    Class "<<interface>>\nStorage" as Storage STORAGE_COLOR
    Class StorageManager STORAGE_COLOR
}

Class HiddenOutside #FFFFFF
HiddenOutside .[LOGIC_COLOR].> Logic

LogicManager .up[LOGIC_COLOR].|> Logic
StorageManager .up[STORAGE_COLOR].|> Storage

LogicManager -[LOGIC_COLOR]-> "Model component"
LogicManager -[LOGIC_COLOR]-> Storage
@enduml
