@startuml
!include style.puml
skinparam arrowThickness 1.1


package Logic LOGIC_COLOR_BACKGROUND {
Class "<<interface>>\nLogic" as Logic LOGIC_COLOR
Class LogicManager LOGIC_COLOR
}

package Model MODEL_COLOR_BACKGROUND {
Class "<<interface>>\nModel" as Model MODEL_COLOR
Class ModelManager MODEL_COLOR
}

package Storage STORAGE_COLOR_BACKGROUND {
Class "<<interface>>\nStorage" as Storage STORAGE_COLOR
Class StorageManager STORAGE_COLOR
}

Class HiddenOutside #FFFFFF
HiddenOutside .up.> Logic

LogicManager .[LOGIC_COLOR]left.|> Logic
ModelManager .[MODEL_COLOR]left.|> Model
StorageManager .[STORAGE_COLOR]left.|> Storage

LogicManager -[LOGIC_COLOR]right-> Model
LogicManager -[LOGIC_COLOR]-> Storage
@enduml
