@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":CompanyCommandParser" as CompanyCommandParser LOGIC_COLOR
participant ":CompanyCommand" as CompanyCommand LOGIC_COLOR
participant ":CompanyContainsKeywordsPredicate" as CompanyContainsKeywordsPredicate LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box


box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("company Google")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("company Google")
activate AddressBookParser

create CompanyCommandParser
AddressBookParser -> CompanyCommandParser
activate CompanyCommandParser

CompanyCommandParser --> AddressBookParser
deactivate CompanyCommandParser

AddressBookParser -> CompanyCommandParser : parse("Google")
activate CompanyCommandParser

create CompanyCommand
CompanyCommandParser -> CompanyCommand
activate CompanyCommand

CompanyCommand --> CompanyCommandParser
deactivate CompanyCommand

create CompanyContainsKeywordsPredicate
CompanyCommand -> CompanyContainsKeywordsPredicate
activate CompanyContainsKeywordsPredicate

CompanyContainsKeywordsPredicate --> CompanyCommand
deactivate CompanyContainsKeywordsPredicate


CompanyCommandParser --> AddressBookParser
deactivate CompanyCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
CompanyCommandParser -[hidden]-> AddressBookParser
destroy CompanyCommandParser

AddressBookParser --> LogicManager
deactivate AddressBookParser


LogicManager -> CompanyCommand : execute(model)
activate CompanyCommand


CompanyCommand -> Model : updateFilteredRoleList()
activate Model

Model --> CompanyCommand
deactivate Model

create CommandResult
CompanyCommand -> CommandResult
activate CommandResult

CommandResult --> CompanyCommand
deactivate CommandResult

CompanyCommand --> LogicManager
deactivate CompanyCommand

[<--LogicManager
deactivate LogicManager
@enduml
