@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package "Course   " <<Rectangle>>{
Class Course
Class CourseList

Course *--> "1" String
}

@enduml
