@startuml
'https://plantuml.com/activity-diagram-beta

start
:ModCheck requests Student to enter a new password;
:Student enters a new password;
:ModCheck requests Student to re-enter password;
:Student re-enters password;
if () then ([passwords do not match])
    :ModCheck displays error message;
    :Student enters both passwords correctly;
else ([else])
    endif
stop

@enduml
