@startuml
!include style.puml

skinparam defaultFontSize 40
skinparam SequenceReferencebackgroundColor LightYellow

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ConnectUsParser" as ConnectUsParser LOGIC_COLOR
participant ":DeleteTagFromPersonCommandParser" as DeleteTagFromPersonCommandParser LOGIC_COLOR
participant ":DeleteTagFromPersonCommand" as DeleteTagFromPersonCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Person" as Person MODEL_COLOR
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute(input)
activate LogicManager

LogicManager -> ConnectUsParser : parseCommand(input)
activate ConnectUsParser

create DeleteTagFromPersonCommandParser
ConnectUsParser -> DeleteTagFromPersonCommandParser++
return

ConnectUsParser -> DeleteTagFromPersonCommandParser : parse(args)
activate DeleteTagFromPersonCommandParser

create DeleteTagFromPersonCommand
DeleteTagFromPersonCommandParser -> DeleteTagFromPersonCommand++
return

return DeleteTagFromPersonCommand
destroy DeleteTagFromPersonCommandParser

return DeleteTagFromPersonCommand


LogicManager->DeleteTagFromPersonCommand : execute(model)
activate DeleteTagFromPersonCommand

DeleteTagFromPersonCommand -> Model : getFilteredPersonList()
activate Model
return

create Person
DeleteTagFromPersonCommand -> Person++ : Person(personToEdit, editedRemarks, editedModules, editedCcas, editedMajors)
return

DeleteTagFromPersonCommand -> Model : setPerson(personToEdit, editedPerson)
activate Model
return

DeleteTagFromPersonCommand -> Model : updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)
activate Model
return

create CommandResult
DeleteTagFromPersonCommand ->CommandResult++
return

return commandResult
return

@enduml
