@startuml
skinparam defaultTextAlignment center

start
:User enters delete cases\nby date command;
if () then ([indexes and dates\nnot mixed])
if () then ([date and date range\nnot mixed])
if () then ([date is valid])
    :Deletes cases associated\nwith the given date;
    :Displays\nsuccess message;
    stop
else ([else])
endif
else ([else])
endif
else ([else])
endif
:Displays error message;
stop
@enduml
