@startuml
skinparam defaultTextAlignment center
@startuml
skinparam defaultTextAlignment center

start
:User enters delete cases\nby multiple indexes command;
if () then ([indexes and dates\nnot mixed])
if () then ([all indexes valid])
    :Deletes cases associated\nwith each index;
    :Displays\nsuccess message;
    stop
else ([else])
endif
else ([else])
endif
:Displays error message;
stop
@enduml
