@startuml
!include style.puml

start
:User wants to delete contact details;
:User enters 'delete' command;

if () then (Index or Name is valid)
  :ModCheck deletes contact(s);
else (Index or Name is invalid)
  :ModCheck displays error message;
endif


stop
@enduml