@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":CareFlowLogicManager" as CareFlowLogicManager LOGIC_COLOR
participant ":CareFlowParser" as CareFlowParser LOGIC_COLOR
participant ":PatientParser" as PatientParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "deleteCommand:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> CareFlowLogicManager : execute("p delete 1")
activate CareFlowLogicManager

CareFlowLogicManager -> CareFlowParser : parseCommand("p delete 1")
activate CareFlowParser

create PatientParser
CareFlowParser -> PatientParser
activate PatientParser


create DeleteCommandParser
PatientParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> PatientParser
deactivate DeleteCommandParser

PatientParser --> CareFlowParser
deactivate PatientParser

CareFlowParser -> PatientParser : parse("delete 1")
activate PatientParser
PatientParser -> DeleteCommandParser : parse("1")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : deleteCommand
deactivate DeleteCommand

DeleteCommandParser --> PatientParser : deleteCommand
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> PatientParser
destroy DeleteCommandParser

PatientParser -> CareFlowParser : deleteCommand
deactivate PatientParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
PatientParser -[hidden]-> CareFlowParser
destroy PatientParser

CareFlowParser --> CareFlowLogicManager : deleteCommand
deactivate CareFlowParser

CareFlowLogicManager -> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> Model : deletePatient(1)
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> CareFlowLogicManager : commandResult
deactivate DeleteCommand

[<--CareFlowLogicManager : commandResult
deactivate CareFlowLogicManager
@enduml
