@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":FitBookParser" as FitBookParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box FitBookModel MODEL_COLOR_T1
participant ":FitBookModel" as FitBookModel MODEL_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> FitBookParser : parseCommand("delete 1")
activate FitBookParser

create DeleteCommandParser
FitBookParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> FitBookParser
deactivate DeleteCommandParser

FitBookParser -> DeleteCommandParser : parse("1")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : d
deactivate DeleteCommand

DeleteCommandParser --> FitBookParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> FitBookParser
destroy DeleteCommandParser

FitBookParser --> LogicManager : d
deactivate FitBookParser

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> FitBookModel : deleteClient(1)
activate FitBookModel

FitBookModel --> DeleteCommand
deactivate FitBookModel

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
