@startuml
skinparam activity {
    ArrowColor #A80036
    BackgroundColor #FEFECE
    BorderColor #A80036
    BorderThickness 1.5
}
start
:User executes delete command;
if () then ([User confirms deletion])
    :Find patient to delete;
    :Delete patient from the model;
else ([else])
    :List all patients;
endif
stop

@enduml
