@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":FriendlyLinkParser" as FriendlyLinkParser LOGIC_COLOR
participant ":DeleteElderlyCommandParser" as DeleteElderlyCommandParser LOGIC_COLOR
participant "d:DeleteElderlyCommand" as DeleteElderlyCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete_elderly S1234567I")
activate LogicManager

LogicManager -> FriendlyLinkParser : parseCommand("delete_elderly S1234567I")
activate FriendlyLinkParser

create DeleteElderlyCommandParser
FriendlyLinkParser -> DeleteElderlyCommandParser
activate DeleteElderlyCommandParser

DeleteElderlyCommandParser --> FriendlyLinkParser
deactivate DeleteElderlyCommandParser

FriendlyLinkParser -> DeleteElderlyCommandParser : parse("S1234567I")
activate DeleteElderlyCommandParser

create DeleteElderlyCommand
DeleteElderlyCommandParser -> DeleteElderlyCommand
activate DeleteElderlyCommand

DeleteElderlyCommand --> DeleteElderlyCommandParser : d
deactivate DeleteElderlyCommand

DeleteElderlyCommandParser --> FriendlyLinkParser : d
deactivate DeleteElderlyCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteElderlyCommandParser -[hidden]-> FriendlyLinkParser
destroy DeleteElderlyCommandParser

FriendlyLinkParser --> LogicManager : d
deactivate FriendlyLinkParser

LogicManager -> DeleteElderlyCommand : execute()
activate DeleteElderlyCommand

DeleteElderlyCommand -> Model : getElderly(targetNric)
activate Model

Model --> DeleteElderlyCommand : elderlyToDelete
deactivate Model

DeleteElderlyCommand -> Model : deleteElderly(elderlyToDelete)
activate Model

Model --> DeleteElderlyCommand
deactivate Model

create CommandResult
DeleteElderlyCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteElderlyCommand
deactivate CommandResult

DeleteElderlyCommand --> LogicManager : result
deactivate DeleteElderlyCommand

[<--LogicManager
deactivate LogicManager
@enduml
