@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":QuickBookParser" as QuickBookParser LOGIC_COLOR
participant ":EditCommandParser" as EditCommandParser LOGIC_COLOR
participant "d:EditCommand" as EditCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("edit n/Bob")
activate LogicManager

LogicManager -> QuickBookParser : parseCommand("edit n/bob")
activate QuickBookParser

create EditCommandParser
QuickBookParser -> EditCommandParser
activate EditCommandParser

EditCommandParser --> QuickBookParser
deactivate EditCommandParser

QuickBookParser -> EditCommandParser : parse("n/bob")
activate EditCommandParser

create EditCommand
EditCommandParser -> EditCommand
activate EditCommand

EditCommand --> EditCommandParser : d
deactivate EditCommand

EditCommandParser --> QuickBookParser : d
deactivate EditCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
EditCommandParser -[hidden]-> QuickBookParser
destroy EditCommandParser

QuickBookParser --> LogicManager : d
deactivate QuickBookParser

LogicManager -> EditCommand : execute()
activate EditCommand

EditCommand -> Model : EditPerson()
activate Model

Model --> EditCommand
deactivate Model

create CommandResult
EditCommand -> CommandResult
activate CommandResult

CommandResult --> EditCommand
deactivate CommandResult

EditCommand --> LogicManager : result
deactivate EditCommand

[<--LogicManager
deactivate LogicManager
@enduml
