@startuml
start
:User executes EditEvent command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([parameters are valid])
    :Edit the specified
    event according to the
    parameters given;
    :Check through list of
    ALL persons to edit the
    specified event accordingly;
    :EditEvent Command has been
    successfully executed;
else ([else])
    :An error message is shown;
    :No changes have been made;
endif
stop
@enduml
