@startuml
!pragma useVerticalIf on
start
:User enters edit command;
if () then ([else])
  :Error: Invalid index provided;
  stop
([Positive integer provided]) elseif () then ([else])
  :Error: Invalid command format;
  stop
([At least one field to be edited is provided]) elseif () then ([else])
    :Error: Invalid index provided;
    stop
([Applicant index is in valid range of Applicant list]) elseif () then ([else])
    :Error: Applicant already exists;
    stop
else ([Edited Applicant does not share a name and phone
with any other Applicant])
endif
:Edit Command successfully executes;
stop
@enduml

