@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":EditXCommandParser" as EditXCommandParser LOGIC_COLOR
participant "x:EditXCommand" as EditXCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("editX args*")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("editX args*")
activate AddressBookParser

create EditXCommandParser
AddressBookParser -> EditXCommandParser
activate EditXCommandParser

EditXCommandParser --> AddressBookParser
deactivate EditXCommandParser

AddressBookParser -> EditXCommandParser : parse("args*")
activate EditXCommandParser

create EditXCommand
EditXCommandParser -> EditXCommand
activate EditXCommand

EditXCommand --> EditXCommandParser : x
deactivate EditXCommand

EditXCommandParser --> AddressBookParser : x
deactivate EditXCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
EditXCommandParser -[hidden]-> AddressBookParser
destroy EditXCommandParser

AddressBookParser --> LogicManager : x
deactivate AddressBookParser

LogicManager -> EditXCommand : execute()
activate EditXCommand

EditXCommand -> Model : editX(x)
activate Model

Model --> EditXCommand
deactivate Model

create CommandResult
EditXCommand -> CommandResult
activate CommandResult

CommandResult --> EditXCommand
deactivate CommandResult

EditXCommand --> LogicManager : result
deactivate EditXCommand

[<--LogicManager
deactivate LogicManager
@enduml
