@startuml
'https://plantuml.com/class-diagram
!include style.puml

package logic {

    package commands {
        Class "{abstract}\nCommand" as Command #9AEA54
        Class EditTaskCommand #61B417 extends Command

        Class EditTaskDescriptor #61B417
        EditTaskCommand +-- EditTaskDescriptor
    }

    package parser {
    Class "<<interface>>\nParser" as Parser #18F2D8
    Class EditTaskCommandParser #15B4A1 implements Parser



}

@enduml
