@startuml
start
:User inputs Edit command;
:CodocParser reads user input and recognises the edit command;
:EditCommandParser reads the arguments;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([has arguments])
    :create person descriptor;
    if () then ([prefix are present])
        :Update person descriptor with respective attributes;
    else ([else])
    endif
    if () then ([some fields are edited])
        :Return EditCommand to be executed;
    else ([no fields are edited])
        :throw person not edited error message;
    endif
else ([else])
    :throw invalid command format error message;
endif
stop
@enduml
