@startuml
start
:EditCommand checks if command can execute;
:Get personToEdit from Model;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([Edit removes any skills])
    :Check original set of skills;
    if () then ([Any removed skill does not exist in original set])
        :throw skill does not exist error message;
    endif
else ([else])
endif
if () then ([Edit removes any modules])
    :Check original set of modules;
    if () then ([Any removed module does not exist in original set])
        :throw module does not exist error message;
    else ([else])
    endif
else ([else])
endif
:EditCommand executes;
stop
@enduml
