@startuml
!include style.puml

box ApplicationLogic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":InternshipBookParser" as InternshipBookParser LOGIC_COLOR
participant ":EditApplicationCommandParser" as EditApplicationCommandParser LOGIC_COLOR
participant "d:EditApplicationCommand" as EditApplicationCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":Application" as Application MODEL_COLOR
end box

note left of LogicManager #aqua
Let user input be <str>
str = "1 r/SYSTEMS ANALYST c/HRT
e/HRThires@gmail.com s/applied"
end note

[-> LogicManager : execute("edit {str}")
activate LogicManager

LogicManager -> InternshipBookParser : parseCommand("edit {str}")
activate InternshipBookParser

create EditApplicationCommandParser
InternshipBookParser -> EditApplicationCommandParser
activate EditApplicationCommandParser

EditApplicationCommandParser --> InternshipBookParser
deactivate EditApplicationCommandParser

InternshipBookParser -> EditApplicationCommandParser : parse("{str}")
activate EditApplicationCommandParser

create Application
EditApplicationCommandParser -> Application
activate Application

Application --> EditApplicationCommandParser : app
deactivate Application

create EditApplicationCommand
EditApplicationCommandParser -> EditApplicationCommand : new EditApplicationCommand(app)
activate EditApplicationCommand

EditApplicationCommand --> EditApplicationCommandParser : editCommand
deactivate EditApplicationCommand

EditApplicationCommandParser --> InternshipBookParser : editCommand
deactivate EditApplicationCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
EditApplicationCommandParser -[hidden]-> InternshipBookParser
destroy EditApplicationCommandParser

InternshipBookParser --> LogicManager : editCommand
deactivate InternshipBookParser

LogicManager -> EditApplicationCommand : execute()
activate EditApplicationCommand

EditApplicationCommand -> Model : editApplication(app)
activate Model

Model --> EditApplicationCommand
deactivate Model

create CommandResult
EditApplicationCommand -> CommandResult
activate CommandResult

CommandResult --> EditApplicationCommand
deactivate CommandResult

EditApplicationCommand --> LogicManager : result
deactivate EditApplicationCommand

[<--LogicManager
deactivate LogicManager

@enduml
