@startuml

start
:User executes command;

if() then ([valid syntax])
    :Executes edit command;

    if() then ([valid arguments])
        :Edit person in addressBook;

    else([else])
        endif

else([else])
    endif

stop

@enduml
