@startuml
!include style.puml

box Ui UI_COLOR_T1
participant ":StudentLisCard" as StudentListCard UI_COLOR
participant ":MainWindow" as MainWindow UI_COLOR
participant ":HeaderBar" as HeaderBar UI_COLOR
participant ":DetailedInfoSection" as DetailedInfoSection UI_COLOR
participant ":FilledExamsContent" as FilledExamsContent UI_COLOR
participant ":EmptyExamsContent" as EmptyExamsContent UI_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Student" as Student MODEL_COLOR
participant ":Name" as Name MODEL_COLOR
end box

[-> StudentListCard : handleViewLessonsButtonClick()
activate StudentListCard

StudentListCard -> Student : getFullName()
activate Student

Student --> Name : getFirstName()
activate Name
return firstName

return firstName

StudentListCard -> MainWindow : setDetailedHeaderBar(firstName)
activate MainWindow

MainWindow -> DetailedInfoSection : setDetailedHeaderBar(firstName)
activate DetailedInfoSection

DetailedInfoSection -> DetailedInfoSection : setHeaderBar(firstName)
activate DetailedInfoSection

create HeaderBar
DetailedInfoSection -> HeaderBar
activate HeaderBar

HeaderBar --> DetailedInfoSection
deactivate HeaderBar

DetailedInfoSection --> DetailedInfoSection
deactivate DetailedInfoSection

DetailedInfoSection --> MainWindow
deactivate DetailedInfoSection

MainWindow --> StudentListCard
deactivate MainWindow

alt student has lessons
    create FilledExamsContent
    StudentListCard -> FilledExamsContent : new FilledExamsContent(student)
    activate FilledExamsContent

    FilledExamsContent -> Student : getName()
    activate Student

    Student --> Name : getFirstName()
    activate Name
    return firstName

    return firstName

    FilledExamsContent -> Student : getExamsList()
    activate Student
    return examsList

    FilledExamsContent -> Student : getUpcomingExamsList()
    activate Student
    return upcomingLessonsList

    FilledExamsContent --> StudentListCard
    deactivate FilledExamsContent

else student has no lessons
    create EmptyExamsContent
    StudentListCard -> EmptyExamsContent : new EmptyExamsContent(student)
    activate EmptyExamsContent

    EmptyExamsContent -> Student : getName()
    activate Student

    Student --> Name : getFirstName()
    activate Name
    return firstName

    return firstName

    EmptyExamsContent --> StudentListCard
    deactivate EmptyExamsContent

end

StudentListCard -> MainWindow : setDetailedContent()
activate MainWindow

MainWindow -> DetailedInfoSection : setDetailedContent()
activate DetailedInfoSection

DetailedInfoSection -> DetailedInfoSection : setContent()
activate DetailedInfoSection

DetailedInfoSection --> DetailedInfoSection
deactivate DetailedInfoSection

DetailedInfoSection --> MainWindow
deactivate DetailedInfoSection

MainWindow --> StudentListCard
deactivate MainWindow

[<-- StudentListCard
deactivate StudentListCard

@enduml
