@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor FILES_COLOR_T4
skinparam classBackgroundColor FILES_COLOR

package Files <<Rectangle>> {
  Class "<<interface>>\nFiles" as Files
  Class "<<interface>>\nFileReader" as FileReader
  Class "<<interface>>\nFileGenerator" as FileGenerator
  Class FileManager
  Class FileStorage
  Class FileReaderManager
  Class PdfReader
  Class ImageReader
  Class PdfGenerator
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Files
PdfReader .up.|> FileReader
PdfGenerator .up.|> FileGenerator
ImageReader .up.|> FileReader
FileManager .up.|> Files

FileManager -down-> FileReaderManager : 1
FileManager -down-> PdfGenerator : 1
FileManager -down-> FileStorage : 1
FileReaderManager -down-> PdfReader : 1
FileReaderManager -down-> ImageReader : 1

package UI {
Class HiddenModel #FFFFFF
}

PdfReader --> UI : 1
ImageReader --> UI : 1

@enduml
