@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ExecutiveProParser" as ExecutiveProParser LOGIC_COLOR
participant ":FilterCommandParser" as FilterCommandParser LOGIC_COLOR
participant ":FilterCommand" as FilterCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("filter pr > 1000")
activate LogicManager

LogicManager -> ExecutiveProParser : parseCommand("filter pr > 1000")
activate ExecutiveProParser

create FilterCommandParser
ExecutiveProParser -> FilterCommandParser
activate FilterCommandParser

FilterCommandParser --> ExecutiveProParser
deactivate FilterCommandParser

ExecutiveProParser -> FilterCommandParser : parse("pr > 1000")
activate FilterCommandParser

create FilterCommand
FilterCommandParser -> FilterCommand
activate FilterCommand

FilterCommand --> FilterCommandParser :
deactivate FilterCommand

FilterCommandParser --> ExecutiveProParser :
deactivate FilterCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FilterCommandParser -[hidden]-> ExecutiveProParser
destroy FilterCommandParser

ExecutiveProParser --> LogicManager :
deactivate ExecutiveProParser

LogicManager -> FilterCommand : execute()
activate FilterCommand

FilterCommand -> Model : updateFilteredList(predicate)
activate Model

Model --> FilterCommand
deactivate Model

create CommandResult
FilterCommand -> CommandResult
activate CommandResult

CommandResult --> FilterCommand
deactivate CommandResult

FilterCommand --> LogicManager : result
deactivate FilterCommand

[<--LogicManager
deactivate LogicManager
@enduml
