@startuml
'https://plantuml.com/activity-diagram-beta

start
:User enters find command;
if () then ([Name flag
present])
    :Create Name Predicate;
else([else])
endif
if () then ([Phone flag
present])
    :Create Phone Predicate;
else([else])
endif

if () then ([else])
:Apply logical AND to all existing Predicates;
:Find command successfully executes;
stop
else ([No flag present])
:Error: Invalid command format;
stop
@enduml
