@startuml
!include style.puml

skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "listClients"

package States {
    class State1 as "__fb0:FitBook__" #FFFF00
}

class Pointer as "Current State"
Pointer -up-> State1
note right on link: State fb2 deleted.
@enduml
