
@startuml
!include style.puml

box Logic #C8C8FA
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FindPolicyCommandParser" as FindPolicyCommandParser LOGIC_COLOR
participant ":FindPolicyCommand" as FindPolicyCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":PolicyExistInPersonPredicate" as PolicyExistInPersonPredicate MODEL_COLOR
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager: execute("findPolicy Insurance")
activate LogicManager

LogicManager -> AddressBookParser: parseCommand("findPolicy Insurance")
activate AddressBookParser

create FindPolicyCommandParser
AddressBookParser -> FindPolicyCommandParser: parse("Insurance")
activate FindPolicyCommandParser

create PolicyExistInPersonPredicate
FindPolicyCommandParser -> PolicyExistInPersonPredicate: PolicyExistInPersonPredicate("Insurance")
activate PolicyExistInPersonPredicate

PolicyExistInPersonPredicate --> FindPolicyCommandParser
deactivate PolicyExistInPersonPredicate

create FindPolicyCommand
FindPolicyCommandParser -> FindPolicyCommand: FindPolicyCommand()
activate FindPolicyCommand

FindPolicyCommand --> FindPolicyCommandParser
deactivate FindPolicyCommand

FindPolicyCommandParser --> AddressBookParser
deactivate FindPolicyCommandParser

AddressBookParser --> LogicManager
deactivate AddressBookParser

LogicManager -> FindPolicyCommand: execute()
activate FindPolicyCommand

FindPolicyCommand -> Model: updateFilteredPersonList(predicate)
activate Model

Model --> FindPolicyCommand
deactivate Model

Create CommandResult
FindPolicyCommand -> CommandResult: CommandResult()
activate CommandResult

CommandResult --> FindPolicyCommand
deactivate CommandResult

FindPolicyCommand --> LogicManager: CommandResult
deactivate FindPolicyCommand

[<-- LogicManager
deactivate LogicManager
@enduml
