@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":StudentCommandParser" as StudentCommandParser LOGIC_COLOR
end box

[-> LogicManager : execute("student 1A grade in/25 test/CA1 score/75")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("student 1A grade in/25 test/CA1 score/75")
activate AddressBookParser

AddressBookParser -> StudentCommandParser : parse("student 1A grade in/25 test/CA1 score/75")
activate StudentCommandParser

StudentCommandParser -> : parseTest("in/25 test/CA1 score/75", 75")
StudentCommandParser <--
StudentCommandParser ->
StudentCommandParser <-- : commandResult

@enduml
