@startuml
start
if () then ([Internship application list is empty])
:Generate null list message;
else ([else])
:Clear all internship applications with keyword for STATUS;
:Generate success message;
endif
stop
@enduml
