@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class Hospital
Class Name
Class Phone
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Hospital

Hospital *--> "1" Name
Hospital *--> "    1 hotline"  Phone

Name -[hidden]right-> Phone

@enduml