
@startuml
!include StyleHY.puml
'https://plantuml.com/sequence-diagram
hide footbox



participant "<<class>>\nParserUtil" as PU COL4

-> PU : .parseDate("20000101")
activate PU

participant "<<class>>\nDate" as DATE COL2
participant "<<class>>\nLocalDate" as LD COL5
PU -> DATE : isValidDate(\n"20000101")
activate DATE COL2

DATE -> DATE : produceValidationFormat("20000101")
activate DATE COL2
DATE --> DATE : yyyyMMdd
deactivate DATE COL2


DATE -> LD : parse(test, yyyyMMdd)
activate DATE COL2
activate LD COL5
LD --> DATE
deactivate DATE
deactivate LD


DATE --> PU : true
deactivate DATE COL2
create ":Date" as D COL1

PU -> D
activate D COL1

D -> DATE : isValidDate("20000101")
activate DATE COL2
DATE -> DATE : produceValidationFormat("20000101")
activate DATE COL2
DATE --> DATE : yyyyMMdd
deactivate DATE COL2
DATE -> LD : parse(test, yyyyMMdd)
activate DATE COL2
activate LD COL5
LD --> DATE
deactivate DATE
deactivate LD


DATE --> D : true
deactivate DATE

D -> DATE : produceValidationFormat("20000101")
activate DATE COL2
DATE --> D : yyyyMMdd
deactivate DATE

D -> LD : parse("20000101", yyyyMMdd)
activate LD COL5

LD --> D : LocalDate 2000-01-01
deactivate LD

D -> LD : toString()
activate LD COL5
LD --> D : "2000-01-01"
deactivate LD


deactivate DATE COL2
D --> PU
deactivate D COL1

<-- PU
deactivate PU
@enduml
