@startuml
start
:User executes `inc` command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([Valid index specified])
    if () then ([Quantity not specified])
        :WIFE increases quantity by 1;
        stop;
    else ([else])
        if () then ([Valid quantity specified])
            :WIFE increases quantity by specified quantity;
        else ([else])
            :WIFE returns error message;
            stop
        endif
    endif
else ([else])
    :WIFE returns error message;
    stop;
endif
stop
@enduml
