@startuml
!include style.puml

box Ui UI_COLOR_T1
participant ":StudentLisCard" as StudentListCard UI_COLOR
participant ":MainWindow" as MainWindow UI_COLOR
participant ":DetailedInfoSection" as DetailedInfoSection UI_COLOR
participant ":FilledLessonsContent" as FilledLessonsContent UI_COLOR
participant ":EmptyLessonsContent" as EmptyLessonsContent UI_COLOR
end box

[-> StudentListCard : handleViewLessonsButtonClick()
activate StudentListCard


StudentListCard -> MainWindow : setDetailedHeaderBar(firstName)
activate MainWindow

MainWindow -> DetailedInfoSection : setDetailedHeaderBar(firstName)
activate DetailedInfoSection

DetailedInfoSection -> DetailedInfoSection : setHeaderBar(firstName)
activate DetailedInfoSection

DetailedInfoSection --> DetailedInfoSection
deactivate DetailedInfoSection

DetailedInfoSection --> MainWindow
deactivate DetailedInfoSection

MainWindow --> StudentListCard
deactivate MainWindow

alt student has lessons
    create FilledLessonsContent
    StudentListCard -> FilledLessonsContent : new FilledLessonsContent(student)
    activate FilledLessonsContent

    return FilledLessonsContent

else student has no lessons
    create EmptyLessonsContent
    StudentListCard -> EmptyLessonsContent : new EmptyLessonsContent(student)
    activate EmptyLessonsContent

    return EmptyLessonsContent

end

StudentListCard -> MainWindow : setDetailedContent()
activate MainWindow

MainWindow -> DetailedInfoSection : setDetailedContent()
activate DetailedInfoSection

DetailedInfoSection -> DetailedInfoSection : setContent()
activate DetailedInfoSection

DetailedInfoSection --> DetailedInfoSection
deactivate DetailedInfoSection

DetailedInfoSection --> MainWindow
deactivate DetailedInfoSection

MainWindow --> StudentListCard
deactivate MainWindow

[<-- StudentListCard
deactivate StudentListCard

@enduml
