@startuml
!include style.puml
skinparam classBackgroundColor MODEL_COLOR

Class Client

Class UniqueProjectList

Class Project

Client *----> "1\n linked projects" UniqueProjectList
Project -->"0..1\n linked clients" Client
Client .up.> Project
UniqueProjectList -up->"*" Project

@enduml
