@startuml
'https://plantuml.com/activity-diagram-beta

'idea of rake provided @WillySeahh in https://github.com/nus-cs2103-AY1920S2/forum/issues/105

start
:ModCheck checks number of times Student visited ModCheck;
if () then ([Student visited more than once])
    :ModCheck displays default login screen;
    :ModCheck requests Student to login;
    :Student enters password;
    if () then ([password is correct])
    else ([else])
        :ModCheck displays error message;
        :Student re-enters correct password;
    endif
else ([else])
    :ModCheck displays welcome screen;
    :ModCheck requests Student to create a password;
        if () then ([Student wants to create password])
            :Student creates password (@rake CreatePasswordActivityDiagram);
        else ([else])
        endif
endif
        :ModCheck displays loading screen;
stop

@enduml
