@startuml
start
:User executes mark parcel command (mark_pc);

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([valid person index])
    :Retrieve delivery details;
    if () then ([valid parcel index])
    :Retrieve parcel details;
    if () then ([valid status])
        :Update parcel status;
        else ([else])
        :Display error message;
        endif
    else ([else])
    :Display error message;
    endif
    else ([else])
        :Display error message;
endif
stop
@enduml
