@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class "<<interface>>\nReadOnlyStudentList" as ReadOnlyStudentList
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as ModelInterface
Class ClassList
Class ModelManager
Class UserPrefs

Class UniqueStudentList
Class Student
Class Name
Class Attendance
Class Submissions
Class Tag

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> ModelInterface

ClassList .up.|> ReadOnlyStudentList

ModelManager .up.|> ModelInterface
ModelInterface .right.> ReadOnlyUserPrefs
ModelInterface .left.> ReadOnlyStudentList
ModelManager -left-> "1" ClassList
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

ClassList *--> "1" UniqueStudentList
UniqueStudentList --> "~* all" Student
Student *--> Submissions
Student *--> Attendance
Student *--> Name
Student *--> "*" Tag

Name -[hidden]right-> Attendance

ModelManager -->"~* filtered" Student
@enduml