@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueTagList
AddressBook *-down-> "1" UniqueGroupList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniquePersonList
UniqueGroupList -down-> Group
Group -right-> Person

UniqueTagList -right-> "*" Tag
UniquePersonList -right-> Person

Person -up-> "*" Tag
@enduml
