@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class "<<interface>>\nReadOnlyEventBook" as ReadOnlyEventBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nReadOnlyContactList" as ReadOnlyConatctList
Class "<<interface>>\nModel" as Model

Class EventBook
Class ModelManager
Class UserPrefs
Class ContactList
Class Contact

Class UniqueEventList
Class Event

Class UniqueContactList
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

EventBook .up.|> ReadOnlyEventBook
ContactList .up.|> ReadOnlyConatctList

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyEventBook
Model .> ReadOnlyConatctList

ModelManager -right-> "1" UserPrefs
ModelManager -> "1" EventBook
ModelManager -> "1" ContactList
UserPrefs .up.|> ReadOnlyUserPrefs

ContactList *--> "1" UniqueContactList
UniqueContactList --> "     ~* all" Contact
EventBook *--> "1" UniqueEventList
UniqueEventList --> "~* all" Event

Event *--> "0..1  " Contact


ModelManager -->"~* filtered" Event
@enduml
