@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Keyword\n <<Rectangle>>{
Class Keyword

Class String
}

KeywordManager -> "~* all" Keyword

Keyword *--> "keyword 1" String
Keyword *--> "1 mainKeyword" String

@enduml
