@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class "<<interface>>\nReadOnlyRecipeBook" as ReadOnlyRecipeBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model_
Class RecipeBook
Class ModelManager
Class UserPrefs

Class UniqueRecipeList
Class Recipe
Class RecipePortion
Class Name
Class RecipeDuration
Class Tag
Class Step
Class Ingredient
Class IngredientBuilder
Class IngredientParser
Class IngredientInformation
}

Class HiddenOutside #FFFFFF

HiddenOutside .down.> Model_

ModelManager .up.|> Model_
RecipeBook .up.|> ReadOnlyRecipeBook

Model_ .left.> ReadOnlyUserPrefs
Model_ .right.> ReadOnlyRecipeBook
ModelManager -left-> "1" RecipeBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

RecipeBook *--> "1" UniqueRecipeList
UniqueRecipeList --> "~* all" Recipe
Recipe *--l-> "1" Name
Recipe *---> "*" Tag
Recipe *---> "*" Step
Recipe *---> "0..1" RecipeDuration
Recipe *---> "0..1" RecipePortion
Recipe *-right-> "*" Ingredient
Recipe *--> "*" IngredientInformation
Recipe .right.> IngredientBuilder

IngredientBuilder ..> Ingredient
IngredientBuilder ..> IngredientInformation
IngredientBuilder .u.> IngredientParser
ModelManager -->"~* filtered" Recipe
@enduml
