@startuml

title New Session initialised


!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

class Session as "hall:Session"

Session *-> SessionName
Session *--> AttendanceMap
Session *--> sessionTime
Session *---> PayRateMap
Session *--> Location



class AttendanceMap as "EmptyAttendanceMap"



@enduml
