@startuml
skinparam defaultTextAlignment center
start
:User executes next command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([invalid argument])
    :Response Box shows
    invalid argument message;
stop
else ([else])
switch ()
case ( [index given])
    :Filter out the next X (where X = index)
    ongoing/upcoming events;
case ( [else])
    :Filter out the next (only one)
    ongoing/upcoming event;

endswitch
:Update events list panel to show the filtered event(s);
:Success message is returned;
stop
@enduml
