@startuml

start
:User inputs 'review DECK_INDEX' to enter REVIEW_MODE;
:User completes review of the first card;
:User inputs ']' command to move on to next card;

if () then ([Current card is last card])
    :Inform user that this
    was the last card;
else ([Next card exists])
    :Display next flashcard;


endif

stop
@enduml
