@startuml
object Course
object Group
object Student
object Session
object Task


object Course {
  courseCode:String
}

object Group {
  groupName : String
}

object Session {
 sessionName : String
}

object Task {
 taskName : String
}

object Student {
 name : Name
 phone : Phone
 email : Email
 remark : Remark
 studentId : StudentId
}

Course -> "*" Group
Group -> "*" Student
Group -> "*" Session
Group -> "*" Task




@enduml
