@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":PowerConnectParser" as PowerConnectParser LOGIC_COLOR
participant ":ParentCommandParser" as ParentCommandParser LOGIC_COLOR
participant "<<class>>\n ParserUtil" as ParserUtil LOGIC_COLOR
participant ":ParentAddCommand" as ParentAddCommand LOGIC_COLOR
participant "newParent:Parent" as Parent LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
end box


[-> LogicManager : execute("parent add n/Tan Ah Niu pnP/91234567")
activate LogicManager

LogicManager -> PowerConnectParser : parseCommand("parent add n/Tan Ah Niu pnP/91234567")
activate PowerConnectParser
create ParentCommandParser

PowerConnectParser -> ParentCommandParser :
activate ParentCommandParser

ParentCommandParser --> PowerConnectParser:
deactivate ParentCommandParser

PowerConnectParser -> ParentCommandParser: parse("add n/Tan Ah Niu pnP/91234567")
activate ParentCommandParser

ParentCommandParser -> ParentCommandParser: addCommand(ArgumentMultimap)
activate ParentCommandParser
create ParentAddCommand

ref over ParentCommandParser, ParserUtil
    get parent particulars

end ref

ParentCommandParser -> ParentAddCommand: ParentAddCommand(...)
activate ParentAddCommand

ParentAddCommand --> ParentCommandParser:
deactivate ParentAddCommand

ParentCommandParser -> ParentCommandParser
deactivate ParentCommandParser

ParentCommandParser --> PowerConnectParser
deactivate ParentCommandParser

PowerConnectParser --> LogicManager
deactivate PowerConnectParser

LogicManager -> ParentAddCommand: execute(Model)
activate ParentAddCommand

ParentAddCommand -> ModelManager: hasParent(Parent)
activate ModelManager

ModelManager --> ParentAddCommand
deactivate ModelManager

ParentAddCommand -> ModelManager: addParent(Parent)
activate ModelManager

ModelManager --> ParentAddCommand
deactivate ModelManager

ParentAddCommand --> LogicManager
deactivate ParentAddCommand

[<--LogicManager
deactivate LogicManager

@enduml
