@startuml
!include style.puml
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "<<interface>>\nCommand" as Command
Class XYZCommand

package "Parser classes"{
    Class VimificationParser
    Class ApplicativeParser
    Class "<<interface>>\nCommandParser" as CommandParser
    Class XYZCommandParser
    Class CommandParserUtil
    Class ArgumentCounter
    Class "<<interface>>\nArgumentFlag" as ArgumentFlag
    Class LiteralArgumentFlag
    Class ComposedArgumentFlag
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> VimificationParser

VimificationParser --> "*" CommandParser
VimificationParser ..> ApplicativeParser

XYZCommandParser ..> XYZCommand : creates >
VimificationParser ..> Command : returns >

XYZCommandParser .up.|> CommandParser
XYZCommandParser ..> ApplicativeParser
XYZCommandParser ..> ArgumentCounter
XYZCommandParser ..> ArgumentFlag
XYZCommandParser ..> CommandParserUtil

XYZCommand .up.|> Command
LiteralArgumentFlag .up.|> ArgumentFlag
ComposedArgumentFlag .up.|> ArgumentFlag

@enduml
