@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package PatientModel <<Rectangle>>{
Class Patient
Class Name
Class Phone
Class Email
Class Address
Class DateOfBirth
Class Gender
Class Ic
Class DrugAllergy
Class UniquePatientList
}

Class PatientRecord
PatientRecord *--> UniquePatientList
UniquePatientList -right-> Patient

Patient *--> "1" Name
Patient *--> "1" Email
Patient *--> "1" Address
Patient *--> "1" DateOfBirth
Patient *--> "1" Gender
Patient *--> "1" Ic
Patient *--> "0..1" DrugAllergy
Patient *--> "1" Phone
Patient *--> "\lEmergency\ncontact\n0..1" Phone :\n\n\n\n

Name -[hidden]right-> Email
Email -[hidden]right-> Address
Address -[hidden]right-> DateOfBirth
DateOfBirth -[hidden]right-> Gender
Gender -[hidden]right-> Ic
Ic -[hidden]right-> DrugAllergy
DrugAllergy -[hidden]right-> Phone

@enduml
