@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package PatientModel <<Rectangle>>{
Class Patient
Class Name
Class Phone
Class Email
Class Address
Class DateOfBirth
Class Gender
Class Ic
Class DrugAllergy
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Patient

Patient *--> "1" Name
Patient *--> "1" Phone
Patient *--> "0..1" Phone
note on link
Represents
emergency
contact
phone
number
of patient.
endnote
Patient *--> "1" Email
Patient *--> "1" Address
Patient *--> "1" DateOfBirth
Patient *--> "1" Gender
Patient *--> "1" Ic
Patient *--> "0..1" DrugAllergy

Name -[hidden]right-> Email
Email -[hidden]right-> Address
Address -[hidden]right-> Phone
Phone -[hidden]right-> DateOfBirth
DateOfBirth -[hidden]right-> Gender
Gender -[hidden]right-> Ic
Ic -[hidden]right-> DrugAllergy

@enduml
