@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package PersonModel <<Rectangle>>{
Class Person
Class Address
Class Email
Class Name
Class Phone
Class Tag

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> "*" Tag

}
