@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class Patient
Class Medication
Class Cost
class AddressBook

Patient -> "*" Medication
Medication *--> "1" Cost
AddressBook -Left->"*" Medication
@enduml
