@startuml
'https://plantuml.com/class-diagram
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR
skinparam classBackgroundColor LOGIC_COLOR


package Recommender LOGIC_COLOR_BACKGROUND {
    class Recommender
    class TimingRecommender
    class LocationRecommender
    class LocationTracker
}

package Model MODEL_COLOR_BACKGROUND {
    class Person MODEL_COLOR
    class Location MODEL_COLOR
    class TimePeriod MODEL_COLOR
}

Class HiddenOutside #FFFFFF
HiddenOutside .right.> Recommender

Recommender --> LocationRecommender
Recommender -up-> TimingRecommender
Recommender -right-> "*" LocationTracker

LocationTracker -[hidden]up-> TimingRecommender
LocationTracker -[hidden]down-> LocationRecommender

LocationTracker -up-> "1" Person
LocationTracker --> "*" Location
LocationTracker ..> TimePeriod

TimingRecommender .up.> TimePeriod
TimingRecommender --> "1" Person

LocationRecommender ..> TimePeriod
LocationRecommender -up-> "*" Location

Person -[hidden]up-> TimePeriod
Person -[hidden]down-> Location

@enduml
