@startuml
skinparam defaultTextAlignment center

start
while () is ([end date has not reached])
if () then ([time slot is occupied
    by another event])
        :Response Box
        shows event exists
        at chosen time;
    stop;
    else ([else])
    :Common modules and
    index are computed;
    :Computes the event
    and store it in a list;
    endif
endwhile ([else])
:Add all recurring events from computed list to Ez-Schedule;
stop

@enduml
