@startuml
!include style.puml
skinparam conditionStyle diamond
title Vehicle Removal Activity Diagram
start
:check if vehicle exists;
if () then ([else])
  :throw VehicleNotFoundException;
  stop
else ([vehicle exists])
:push copy of current shop to undo stack;
:clear redo stack;
  repeat: for serviceId in vehicle.getServiceIds()
    :removeService(vehicleId) <$rake>;
  repeat while ([has next]) is (yes) not (no)
  :remove vehicle ID from owner;
  :remove vehicle customer from shop;
  :update customer mappings;
  :update vehicle mappings;
  :set vehicle ID unused in ID generator;
  stop
@enduml
