@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TaskBookParser" as TaskBookParser LOGIC_COLOR
participant ":DeleteSubtaskParser" as DeleteSubtaskParser LOGIC_COLOR
participant "d:DeleteSubtaskCommand" as DeleteSubtaskCommand LOGIC_COLOR
participant "t:SimpleTask" as SimpleTask LOGIC_COLOR
participant "l:Deadline" as Deadline LOGIC_COLOR
participant "v:Event" as Event LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR


end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("remove-subsection 1 I/1")
activate LogicManager

LogicManager -> TaskBookParser : parseCommand("remove-subsection 1 I/1")
activate TaskBookParser

create DeleteSubtaskParser
TaskBookParser -> DeleteSubtaskParser
activate DeleteSubtaskParser

DeleteSubtaskParser --> TaskBookParser
deactivate DeleteSubtaskParser

TaskBookParser -> DeleteSubtaskParser : parse("1 I/1")
activate DeleteSubtaskParser

create DeleteSubtaskCommand
DeleteSubtaskParser -> DeleteSubtaskCommand : (1, 1)
activate DeleteSubtaskCommand

DeleteSubtaskCommand --> DeleteSubtaskParser : d
deactivate DeleteSubtaskCommand

DeleteSubtaskParser --> TaskBookParser : d
deactivate DeleteSubtaskParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteSubtaskParser -[hidden]-> TaskBookParser
destroy DeleteSubtaskParser

TaskBookParser --> LogicManager : a
deactivate TaskBookParser

LogicManager -> DeleteSubtaskCommand : execute()
activate DeleteSubtaskCommand

alt old task is SimpleTask

    DeleteSubtaskCommand -> SimpleTask
    activate SimpleTask

    SimpleTask --> DeleteSubtaskCommand : t (new task)
    deactivate SimpleTask

else old task is Deadline
    DeleteSubtaskCommand -> Deadline
    activate Deadline

    Deadline --> DeleteSubtaskCommand : l (new task)
    deactivate Deadline

else old task is Event
    DeleteSubtaskCommand -> Event
    activate Event

    Event --> DeleteSubtaskCommand : v (new task)
    deactivate Event
end

DeleteSubtaskCommand -> Model : setTask()
activate Model

Model --> DeleteSubtaskCommand
deactivate Model

create CommandResult
DeleteSubtaskCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteSubtaskCommand
deactivate CommandResult

DeleteSubtaskCommand --> LogicManager : result
deactivate DeleteSubtaskCommand

[<--LogicManager
deactivate LogicManager
@enduml
