@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor SCORE_MODEL_COLOR
skinparam classBackgroundColor SCORE_MODEL_COLOR

Class Date
Class ScoreValue
Class Label
Class Student
Class UniqueScoreList
Class Score

Student *--> UniqueScoreList

UniqueScoreList --> "~* " Score

Score *--> "1" Date
Score *--> "1" Label
Score *--> "1" ScoreValue

@enduml
