@startuml
'https://plantuml.com/sequence-diagram
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CalidrParser" as CalidrParser LOGIC_COLOR
participant ":SearchTaskCommandParser" as SearchTaskCommandParser LOGIC_COLOR
participant ":SearchTaskCommand" as SearchTaskCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR_T2
end box

[-> LogicManager : execute("<command to search for tasks>")
activate LogicManager

LogicManager -> CalidrParser : parseCommand("<command to search for tasks>")
activate CalidrParser

create SearchTaskCommandParser
CalidrParser -> SearchTaskCommandParser
activate SearchTaskCommandParser
SearchTaskCommandParser --> CalidrParser
deactivate SearchTaskCommandParser

CalidrParser -> SearchTaskCommandParser : parse("<command to search for tasks>")
activate SearchTaskCommandParser

create SearchTaskCommand
SearchTaskCommandParser -> SearchTaskCommand
activate SearchTaskCommand
SearchTaskCommand --> SearchTaskCommandParser
deactivate SearchTaskCommand

SearchTaskCommandParser --> CalidrParser : command to search for tasks
deactivate SearchTaskCommandParser

CalidrParser --> LogicManager : command to search for tasks
deactivate CalidrParser

LogicManager -> SearchTaskCommand : execute()
activate SearchTaskCommand

SearchTaskCommand -> Model : updateFilteredTaskList()
activate Model
Model --> SearchTaskCommand
deactivate Model

SearchTaskCommand -> Model : getFilteredTaskList()
activate Model
Model --> SearchTaskCommand
deactivate Model

create CommandResult
SearchTaskCommand -> CommandResult
activate CommandResult
CommandResult --> SearchTaskCommand
deactivate CommandResult

SearchTaskCommand --> LogicManager : result
deactivate SearchTaskCommand

[<-- LogicManager
deactivate LogicManager

@enduml
