@startuml
!include style.puml
mainframe **ref** Parse Information Fields

skinparam defaultFontSize 10
skinparam titleFontSize 10

box Logic LOGIC_COLOR_T1
participant ":SearchCommandParser" as SearchCommandParser LOGIC_COLOR
participant "FieldsContainKeywordsPredicate" as FieldsContainKeywordsPredicate LOGIC_COLOR
end box

activate SearchCommandParser

opt ifNamePrefixPresent
    SearchCommandParser->FieldsContainKeywordsPredicate:setKeywords(name)
    activate FieldsContainKeywordsPredicate
    return
end
opt ifNamePrefixPresent
    SearchCommandParser->FieldsContainKeywordsPredicate:setName(name)
    activate FieldsContainKeywordsPredicate
    return
end
opt ifPhonePrefixPresent
    SearchCommandParser->FieldsContainKeywordsPredicate:setPhone(phone)
    activate FieldsContainKeywordsPredicate
    return
end
opt ifEmailPrefixPresent
    SearchCommandParser->FieldsContainKeywordsPredicate:setEmail(email)
    activate FieldsContainKeywordsPredicate
    return
end
opt ifSearchressPrefixPresent
    SearchCommandParser->FieldsContainKeywordsPredicate:setSearchress(address)
    activate FieldsContainKeywordsPredicate
    return
end
opt ifBirthdayPrefixPresent
    SearchCommandParser->FieldsContainKeywordsPredicate:setBirthday(birthday)
    activate FieldsContainKeywordsPredicate
    return
end
opt ifRemarkPrefixPresent
    SearchCommandParser->FieldsContainKeywordsPredicate:setRemark(remarkList)
    activate FieldsContainKeywordsPredicate
    return
end
opt ifModulePrefixPresent
    SearchCommandParser->FieldsContainKeywordsPredicate:setModules(moduleList)
    activate FieldsContainKeywordsPredicate
    return
end
opt ifCcaPrefixPresent
    SearchCommandParser->FieldsContainKeywordsPredicate:setCcas(ccaList)
    activate FieldsContainKeywordsPredicate
    return
end
opt ifMajorPrefixPresent
    SearchCommandParser->FieldsContainKeywordsPredicate:setMajor(majorList)
    activate FieldsContainKeywordsPredicate
    return
end
opt ifInstagramPrefixPresent
    SearchCommandParser->FieldsContainKeywordsPredicate:setInstagram(instagram)
    activate FieldsContainKeywordsPredicate
    return
end
opt ifWhatsappPrefixPresent
    SearchCommandParser->FieldsContainKeywordsPredicate:setWhatsapp(whatsapp)
    activate FieldsContainKeywordsPredicate
    return
end
opt ifTelegramPrefixPresent
    SearchCommandParser->FieldsContainKeywordsPredicate:setTelegram(telegram)
    activate FieldsContainKeywordsPredicate
    return
end

@enduml
