@startuml
!include style.puml
mainframe **ref** Parse Information Fields

skinparam defaultFontSize 15
skinparam titleFontSize 15

box Logic LOGIC_COLOR_T1
participant ":SearchCommandParser" as SearchCommandParser LOGIC_COLOR
participant "FieldsContainKeywordsPredicate" as FieldsContainKeywordsPredicate LOGIC_COLOR
end box

activate SearchCommandParser

opt ifPreamblePresent
    SearchCommandParser->FieldsContainKeywordsPredicate:setKeywords(keywords)
    activate FieldsContainKeywordsPredicate
    return
end
opt ifFieldPrefixPresent
    SearchCommandParser->FieldsContainKeywordsPredicate:setField(fieldKeyword)
    activate FieldsContainKeywordsPredicate
    return
end

@enduml
