@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor SELECT_COLOR



Class AddressBook {
    Index : selectedIndex
    Person : selectedPerson
}


Class ModelManager


Class LogicManager

LogicManager --> ModelManager
ModelManager -> "1" AddressBook

@enduml