@startuml
!include style.puml

box UI UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
participant ":GroupListPanel" as GroupListPanel UI_COLOR
end box

box LOGIC LOGIC_COLOR_T1
participant ":CurrentSelection" as CurrentSelection LOGIC_COLOR
end box

box MODEL MODEL_COLOR_T1
participant ":Group" as Group MODEL_COLOR
end box

[-> MainWindow : execute("select 1")
activate MainWindow

MainWindow -> CurrentSelection : getCurrentPage()
activate CurrentSelection

CurrentSelection --> MainWindow : PageType.GROUP_PAGE
deactivate CurrentSelection


MainWindow -> MainWindow : showGroupPane
activate MainWindow

create GroupListPanel
MainWindow -> GroupListPanel : new GroupListPanel();
activate GroupListPanel

GroupListPanel -> Group : getUnmodifiableFilteredGroupList()
activate Group

Group --> GroupListPanel : ObservableList<Group>
deactivate Group

GroupListPanel --> MainWindow
deactivate GroupListPanel

MainWindow --> MainWindow
deactivate MainWindow

@enduml
