@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ElisterParser" as ElisterParser LOGIC_COLOR
participant "s:ShortcutCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedElister" as VersionedElister MODEL_COLOR
end box
[-> LogicManager : execute("shortcut edit e")
activate LogicManager

LogicManager -> ElisterParser : parseCommand("shortcut edit e")
activate ElisterParser

create UndoCommand
ElisterParser -> UndoCommand
activate UndoCommand

UndoCommand --> ElisterParser
deactivate UndoCommand

ElisterParser --> LogicManager : s
deactivate ElisterParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoElister()
activate Model

Model -> VersionedElister : undo()
activate VersionedElister

VersionedElister -> VersionedElister :resetData(ReadOnlyElister)
VersionedElister --> Model :
deactivate VersionedElister

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
