@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR


SortCommand *-> Comparator
NameComparator -down-|> Comparator
EmailComparator -up-|> Comparator
RemarkComparator -up-|> Comparator
PerformanceComparator -left-|> Comparator
AddressComparator -up-|> Comparator

SortCommand -left- FilteredList

FilteredPersonList -up-|> FilteredList
FilteredLabList -up-|> FilteredList
FilteredConsultationList -right-|> FilteredList
FilteredTutorialList -down-|> FilteredList
@enduml
