@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":SortByClientNameCommandParser" as SortByClientNameCommandParser LOGIC_COLOR
participant "s:SortByClientNameCommand" as SortByClientNameCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("sortByClientName 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("sortClientName 1")
activate AddressBookParser

create SortByClientNameCommandParser
AddressBookParser -> SortByClientNameCommandParser
activate SortByClientNameCommandParser

SortByClientNameCommandParser --> AddressBookParser
deactivate SortByClientNameCommandParser

AddressBookParser -> SortByClientNameCommandParser : parse("1")
activate SortByClientNameCommandParser

create SortByClientNameCommand
SortByClientNameCommandParser -> SortByClientNameCommand
activate SortByClientNameCommand

SortByClientNameCommand --> SortByClientNameCommandParser : s
deactivate SortByClientNameCommand

SortByClientNameCommandParser --> AddressBookParser : s
deactivate SortByClientNameCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
SortByClientNameCommandParser -[hidden]-> AddressBookParser
destroy SortByClientNameCommandParser

AddressBookParser --> LogicManager : s
deactivate AddressBookParser

LogicManager -> SortByClientNameCommand : execute()
activate SortByClientNameCommand


SortByClientNameCommand --> Model : getFilteredClientList()
activate Model

Model --> SortByClientNameCommand
deactivate Model

SortByClientNameCommand --> Model : sort(List<Client>)
activate Model

Model --> SortByClientNameCommand
deactivate Model

create CommandResult
SortByClientNameCommand -> CommandResult
activate CommandResult

CommandResult --> SortByClientNameCommand
deactivate CommandResult

SortByClientNameCommand --> LogicManager : result
deactivate SortByClientNameCommand

[<--LogicManager
deactivate LogicManager

@enduml
