@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic {

Class FindCommandParser
Class SortCommand
Class FindStatusCommand
Class FindDateCommand
Class "{abstract}\nCommand" as Command
}

package Model{

Class NameContainsKeywordsPredicate MODEL_COLOR
Class StatusPredicate MODEL_COLOR
Class "{abstract}\nDatePredicate" as DatePredicate MODEL_COLOR
Class BeforeDatePredicate MODEL_COLOR
Class AfterDatePredicate MODEL_COLOR
Class BetweenDatePredicate MODEL_COLOR

Class CompanyNameComparator MODEL_COLOR
Class InterviewDateComparator MODEL_COLOR
Class JobTitleComparator MODEL_COLOR
}

Class "<<interface>>\nComparator" as Comparator

FindCommand -up-|> Command
FindDateCommand -up[LOGIC_COLOR_T4]-|> FindCommand
FindStatusCommand -up[LOGIC_COLOR_T4]-|> FindCommand
FindCommandParser .up.> FindCommand
FindCommandParser .up.> FindDateCommand
FindCommandParser .up.> FindStatusCommand

BeforeDatePredicate -up[MODEL_COLOR]--|> DatePredicate
AfterDatePredicate -up[MODEL_COLOR]--|> DatePredicate
BetweenDatePredicate --up[MODEL_COLOR]--|> DatePredicate

FindCommand -left->"1" NameContainsKeywordsPredicate
FindDateCommand -left->"1" DatePredicate
FindStatusCommand -left->"1" StatusPredicate

Command ..> Model
@enduml
