@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "PetPal Storage" #F4F6F6{
Class "<<interface>>\nPetPalStorage" as PetPalStorage
Class JsonPetPalStorage
Class JsonSerializablePetPal
Class JsonAdaptedPet
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" PetPalStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> PetPalStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonPetPalStorage .up.|> PetPalStorage
JsonPetPalStorage ..> JsonSerializablePetPal
JsonSerializablePetPal --> "*" JsonAdaptedPet
JsonAdaptedPet --> "*" JsonAdaptedTag

@enduml
