@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as StorageInterface
Class StorageManager

package "AddressBook Storage" #F4F6F6{
Class "<<interface>>\nAddressBookStorage" as AddressBookStorage
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedClient
Class JsonAdaptedAppointment
Class JsonAdaptedPolicy
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> StorageInterface

StorageManager .up.|> StorageInterface
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" AddressBookStorage

StorageInterface -left-|> UserPrefsStorage
StorageInterface -right-|> AddressBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAddressBookStorage .up.|> AddressBookStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableAddressBook --> "*" JsonAdaptedClient
JsonAdaptedClient --> "*" JsonAdaptedPolicy
JsonAdaptedClient --> "1" JsonAdaptedAppointment

@enduml
