@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "ConnectUs Storage" #F4F6F6{
Class "<<interface>>\nConnectUsStorage" as ConnectUsStorage
Class JsonConnectUsStorage
Class JsonSerializableConnectUs
Class JsonAdaptedPerson
Class JsonAdaptedModule
Class JsonAdaptedCca
Class JsonAdaptedMajor
Class JsonAdaptedRemark
Class JsonAdaptedAddress
Class JsonAdaptedEmail
Class JsonAdaptedPhone
Class JsonAdaptedBirthday
Class JsonAdaptedSocialMedia
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" ConnectUsStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> ConnectUsStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonConnectUsStorage .up.|> ConnectUsStorage
JsonConnectUsStorage ..> JsonSerializableConnectUs
JsonSerializableConnectUs --> "*" JsonAdaptedPerson

JsonAdaptedBirthday -[hidden]up-> JsonAdaptedPhone
JsonAdaptedSocialMedia -[hidden]up-> JsonAdaptedEmail

JsonAdaptedPerson --> "0..1" JsonAdaptedAddress
JsonAdaptedPerson --> "0..1" JsonAdaptedEmail
JsonAdaptedPerson --> "0..1" JsonAdaptedPhone
JsonAdaptedPerson --> "0..1" JsonAdaptedBirthday
JsonAdaptedPerson --> "0..1" JsonAdaptedSocialMedia


JsonAdaptedMajor -[hidden]up-> JsonAdaptedModule
JsonAdaptedRemark -[hidden]up-> JsonAdaptedCca

JsonAdaptedPerson --> "*" JsonAdaptedModule
JsonAdaptedPerson --> "*" JsonAdaptedCca
JsonAdaptedPerson --> "0..2" JsonAdaptedMajor
JsonAdaptedPerson --> "*" JsonAdaptedRemark

@enduml
