/'
 'Commonly used styles and colors across diagrams.
 'Refer to https://plantuml-documentation.readthedocs.io/en/latest for a more
 'comprehensive list of skinparams.
 '/


'T1 through T4 are shades of the original color from lightest to darkest

!define UI_COLOR #1D8900
!define UI_COLOR_T1 #83E769
!define UI_COLOR_T2 #3FC71B
!define UI_COLOR_T3 #166800
!define UI_COLOR_T4 #0E4100

!define LOGIC_COLOR #3333C4
!define LOGIC_COLOR_T1 #C8C8FA
!define LOGIC_COLOR_T2 #6A6ADC
!define LOGIC_COLOR_T3 #1616B0
!define LOGIC_COLOR_T4 #101086

!define MODEL_COLOR #9D0012
!define MODEL_COLOR_T1 #F97181
!define MODEL_COLOR_T2 #E41F36
!define MODEL_COLOR_T3 #7B000E
!define MODEL_COLOR_T4 #51000A

!define STORAGE_COLOR #A38300
!define STORAGE_COLOR_T1 #FFE374
!define STORAGE_COLOR_T2 #EDC520
!define STORAGE_COLOR_T3 #806600
!define STORAGE_COLOR_T2 #544400

!define LOGIC_MANAGER_COLOR #8093F1
!define LOGIC_MANAGER_COLOR_T1 #5A72ED
!define LOGIC_MANAGER_COLOR_T2 #3553E9
!define LOGIC_MANAGER_COLOR_T3 #1839DC
!define LOGIC_MANAGER_COLOR_T2 #1430B8

!define ADDRESS_BOOK_PARSER_COLOR #78E0DC
!define ADDRESS_BOOK_PARSER_COLOR_T1 #59D9D5
!define ADDRESS_BOOK_PARSER_COLOR_T2 #37D2CD
!define ADDRESS_BOOK_PARSER_COLOR_T3 #2AB7B2
!define ADDRESS_BOOK_PARSER_COLOR_T2 #229692

!define SORT_COMMAND_PARSER_COLOR #31CB00
!define SORT_COMMAND_PARSER_COLOR_T1 #119822
!define SORT_COMMAND_PARSER_COLOR_T2 #2A7221
!define SORT_COMMAND_PARSER_COLOR_T3 #1E441E
!define SORT_COMMAND_PARSER_COLOR_T2 #152614

!define SORT_COMMAND_COLOR #F29469
!define SORT_COMMAND_COLOR_T1 #EF7A43
!define SORT_COMMAND_COLOR_T2 #EB5F1E
!define SORT_COMMAND_COLOR_T3 #CE4E12
!define SORT_COMMAND_COLOR_T2 #A9400F

!define MODEL_MANAGER_COLOR #D496A7
!define MODEL_MANAGER_COLOR_T1 #CA7D91
!define MODEL_MANAGER_COLOR_T2 #BE6079
!define MODEL_MANAGER_COLOR_T3 #AE4762
!define MODEL_MANAGER_COLOR_T2 #913B52

!define USER_COLOR #000000

skinparam BackgroundColor #FFFFFFF

skinparam Shadowing false

skinparam Class {
    FontColor #FFFFFF
    BorderThickness 1
    BorderColor #FFFFFF
    StereotypeFontColor #FFFFFF
    FontName Arial
}

skinparam Actor {
    BorderColor USER_COLOR
    Color USER_COLOR
    FontName Arial
}

skinparam Sequence {
    MessageAlign center
    BoxFontSize 15
    BoxPadding 0
    BoxFontColor #FFFFFF
    FontName Arial
}

skinparam Participant {
    FontColor #FFFFFFF
    Padding 20
}

skinparam MinClassWidth 50
skinparam ParticipantPadding 10
skinparam Shadowing false
skinparam DefaultTextAlignment center
skinparam packageStyle Rectangle

hide footbox
hide members
hide circle
