/'
 'Commonly used styles and colors across diagrams.
 'Refer to https://plantuml-documentation.readthedocs.io/en/latest for a more
 'comprehensive list of skinparams.
 '/


'LIGHT through VERY_DARK are shades of the original color from lightest to darkest

!define UI_COLOR #009645
!define UI_COLOR_BACKGROUND #e6f5ec
!define UI_COLOR_LIGHT #4db67d
!define UI_COLOR_VERY_LIGHT #99d5b5
!define UI_COLOR_DARK #006930
!define UI_COLOR_VERY_DARK #003c1c

!define LOGIC_COLOR #005EC4
!define LOGIC_COLOR_BACKGROUND #e6eff9
!define LOGIC_COLOR_LIGHT #4d8ed6
!define LOGIC_COLOR_VERY_LIGHT #99bfe7
!define LOGIC_COLOR_DARK #004289
!define LOGIC_COLOR_VERY_DARK #00264e

!define MODEL_COLOR #D42E12
!define MODEL_COLOR_BACKGROUND #fbeae7
!define MODEL_COLOR_LIGHT #e16d59
!define MODEL_COLOR_VERY_LIGHT #eeaba0
!define MODEL_COLOR_DARK #94200d
!define MODEL_COLOR_VERY_DARK #551207

!define STORAGE_COLOR #FA9E0D
!define STORAGE_COLOR_BACKGROUND #fff5e7
!define STORAGE_COLOR_LIGHT #fcbb56
!define STORAGE_COLOR_VERY_LIGHT #fdd89e
!define STORAGE_COLOR_DARK #af6f09
!define STORAGE_COLOR_VERY_DARK #643f05

!define COMMONS_COLOR #9D5B25
!define COMMONS_COLOR_BACKGROUND #f5efe9
!define COMMONS_COLOR_LIGHT #ba8c66
!define COMMONS_COLOR_VERY_LIGHT #d8bda8
!define COMMONS_COLOR_DARK #6e401a
!define COMMONS_COLOR_VERY_DARK #3f240f

!define USER_COLOR #9900AA
!define USER_COLOR_BACKGROUND #f5e6f7
!define USER_COLOR_LIGHT #b84dc4
!define USER_COLOR_VERY_LIGHT #d699dd
!define USER_COLOR_DARK #6b0077
!define USER_COLOR_VERY_DARK #3d0044

!define IMG_COLOR #0099AA
!define IMG_COLOR_BACKGROUND #e6f5f7
!define IMG_COLOR_LIGHT #4db8c4
!define IMG_COLOR_VERY_LIGHT #99d6dd
!define IMG_COLOR_DARK #006b77
!define IMG_COLOR_VERY_DARK #003d44

!define MAIN_COLOR #748477
!define MAIN_COLOR_BACKGROUND #f1f3f1
!define MAIN_COLOR_LIGHT #9EA9A0
!define MAIN_COLOR_VERY_LIGHT #C7CEC9
!define MAIN_COLOR_DARK #515C53
!define MAIN_COLOR_VERY_DARK #2E3530

skinparam BackgroundColor #FFFFFFF

skinparam Shadowing false

skinparam Class {
    FontColor #FFFFFF
    BorderThickness 1
    BorderColor #FFFFFF
    StereotypeFontColor #FFFFFF
    FontName Arial
}

skinparam Actor {
    BorderColor USER_COLOR
    Color USER_COLOR
    FontName Arial
}

skinparam Sequence {
    MessageAlign center
    BoxFontSize 15
    BoxPadding 0
    BoxFontColor #FFFFFF
    FontName Arial
}

skinparam Participant {
    FontColor #FFFFFFF
    Padding 20
}

skinparam MinClassWidth 50
skinparam ParticipantPadding 10
skinparam Shadowing false
skinparam DefaultTextAlignment center
skinparam packageStyle Rectangle
skinparam sequenceReferenceBackgroundColor #C7CEC9

hide footbox
hide members
hide circle
