@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":RecipeBook\nParser" as RecipeBookParser LOGIC_COLOR
participant ":SubCommand\nParser" as SubCommandParser LOGIC_COLOR
participant "s:SubCommand" as SubCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

[-> LogicManager : execute("sub soy sauce")
activate LogicManager

LogicManager -> RecipeBookParser : parseCommand("sub soy sauce")
activate RecipeBookParser

create SubCommandParser
RecipeBookParser -> SubCommandParser
activate SubCommandParser

SubCommandParser --> RecipeBookParser
deactivate SubCommandParser

RecipeBookParser -> SubCommandParser : parse("soy sauce")
activate SubCommandParser

create SubCommand
SubCommandParser -> SubCommand
activate SubCommand

SubCommand --> SubCommandParser : s
deactivate SubCommand

SubCommandParser --> RecipeBookParser : s
deactivate SubCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
SubCommandParser -[hidden]-> RecipeBookParser
destroy SubCommandParser

RecipeBookParser --> LogicManager : s
deactivate RecipeBookParser

LogicManager -> SubCommand : execute()
activate SubCommand

create CommandResult
SubCommand -> CommandResult
activate CommandResult

CommandResult --> SubCommand
deactivate CommandResult

SubCommand --> LogicManager : result
deactivate SubCommand

[<--LogicManager
deactivate LogicManager
@enduml