@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Package Tab {

Class "<<enumeration>>\nTabType" as TabType
Class TabInfo
Class TabUtil

}

Class Index
Class ReadOnlyObjectWrapper

TabUtil -down-> "*" TabInfo
TabUtil --> "1 selectedTabInfo" ReadOnlyObjectWrapper
ReadOnlyObjectWrapper -> "1" TabInfo
TabInfo -down-> Index
TabInfo -down-> TabType

@enduml