@startuml

!include style.puml
box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ElisterParser" as ElisterParser LOGIC_COLOR
participant ":TagCommandParser" as TagCommandParser LOGIC_COLOR
participant "command:TagCommand" as TagCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":FilteredList" as FilteredList MODEL_COLOR
end box

[-> LogicManager : execute("tag 1 gay")
activate LogicManager

LogicManager -> ElisterParser : parseCommand("tag 1 gay")
activate ElisterParser

create TagCommandParser
ElisterParser -> TagCommandParser
activate TagCommandParser

TagCommandParser --> ElisterParser
deactivate TagCommandParser

ElisterParser -> TagCommandParser : parse("1 gay")
activate TagCommandParser

create TagCommand
TagCommandParser -> TagCommand
activate TagCommand

TagCommand --> TagCommandParser : command
deactivate TagCommand

TagCommandParser --> ElisterParser : command
deactivate TagCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
TagCommandParser -[hidden]-> ElisterParser
destroy TagCommandParser

ElisterParser --> LogicManager : command
deactivate ElisterParser

LogicManager -> TagCommand : execute()
activate TagCommand

TagCommand -> Model : getFilteredPersonList()
activate Model

Model -> TagCommand : lastShownList

TagCommand -> FilteredList : get(targetIndex.getZeroBased())
activate FilteredList

FilteredList --> TagCommand : personToTag
deactivate FilteredList

TagCommand -> Model : addTag()
Model --> TagCommand
deactivate Model

create CommandResult
TagCommand -> CommandResult
activate CommandResult

CommandResult --> TagCommand
deactivate CommandResult

TagCommand --> LogicManager : result
deactivate TagCommand

[<--LogicManager
deactivate LogicManager
@enduml
