@startuml
!include style.puml

box Parsing "fun" and "CS2040S"  LOGIC_COLOR_T1
participant ":TagCommandParser" as TagCommandParser LOGIC_COLOR
participant ":ParserUtil" as ParserUtil LOGIC_COLOR
participant "t:Tag" as Tag LOGIC_COLOR
participant "c:ModuleCode" as ModuleCode LOGIC_COLOR

end box

activate TagCommandParser

TagCommandParser -> ParserUtil : parseMultiTags("fun")
activate ParserUtil

create Tag
ParserUtil -> Tag : "fun"
activate Tag

Tag --> ParserUtil : t
deactivate Tag

ParserUtil --> TagCommandParser : t
deactivate ParserUtil

TagCommandParser -> TagCommandParser : isTaggingMod(tag prefix "/tags")
activate TagCommandParser

TagCommandParser --> TagCommandParser : true
deactivate TagCommandParser

TagCommandParser -> ParserUtil : parseModuleCode("CS2040S")
activate ParserUtil

create ModuleCode
ParserUtil -> ModuleCode : "CS2040S"
activate ModuleCode

ModuleCode --> ParserUtil : c
deactivate ModuleCode

ParserUtil --> TagCommandParser :c
deactivate ParserUtil
deactivate TagCommandParser

@enduml
