@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":DukeDriverParser" as DukeDriverParser LOGIC_COLOR
participant "t:TimetableCommand" as TimetableCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute("timetable")
activate LogicManager

LogicManager -> DukeDriverParser : parseCommand("timetable")
activate DukeDriverParser

create TimetableCommand
DukeDriverParser -> TimetableCommand
activate TimetableCommand

TimetableCommand --> DukeDriverParser : t
deactivate TimetableCommand

DukeDriverParser --> LogicManager : t
deactivate DukeDriverParser

LogicManager -> TimetableCommand : execute()
activate TimetableCommand
TimetableCommand -> Model : updateFocusDate(LocalDate.now())
TimetableCommand -> Model : updateSortedDeliveryJobList(new SortbyTimeAndEarn())
TimetableCommand -> Model : updateSortedDeliveryJobListByDate()
TimetableCommand -> Model : updateWeekDeliveryJobList(LocalDate.now())
activate Model


Model --> TimetableCommand
deactivate Model

TimetableCommand --> LogicManager : result
deactivate TimetableCommand
TimetableCommand -[hidden]-> LogicManager : result
destroy TimetableCommand

[<--LogicManager
deactivate LogicManager
@enduml
