@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":DukeDriverParser" as DukeDriverParser LOGIC_COLOR
participant ":TimetableDateCommandParser" as TimetableDateCommandParser LOGIC_COLOR
participant "t:TimetableDateCommand" as TimetableDateCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute("timetable_date date/2023-03-03")
activate LogicManager

LogicManager -> DukeDriverParser : parseCommand("timetable_date date/2023-03-03")
activate DukeDriverParser

create TimetableDateCommandParser
DukeDriverParser -> TimetableDateCommandParser
activate TimetableDateCommandParser

TimetableDateCommandParser --> DukeDriverParser
deactivate TimetableDateCommandParser

DukeDriverParser -> TimetableDateCommandParser : parse("2023-03-03")
activate TimetableDateCommandParser

create TimetableDateCommand
TimetableDateCommandParser -> TimetableDateCommand
activate TimetableDateCommand

TimetableDateCommand --> TimetableDateCommandParser : t
deactivate TimetableDateCommand

TimetableDateCommandParser --> DukeDriverParser : t
deactivate TimetableDateCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
TimetableDateCommandParser -[hidden]-> DukeDriverParser
destroy TimetableDateCommandParser

DukeDriverParser --> LogicManager : t
deactivate DukeDriverParser

LogicManager -> TimetableDateCommand : execute()

activate TimetableDateCommand

TimetableDateCommand -> Model : updateFocusDate(LocalDate.now())
TimetableDateCommand -> Model : updateSortedDeliveryJobList(new SortbyTimeAndEarn())
TimetableDateCommand -> Model : updateSortedDeliveryJobListByDate()
TimetableDateCommand -> Model : updateWeekDeliveryJobList(LocalDate.now())
activate Model

Model --> TimetableDateCommand
deactivate Model

TimetableDateCommand --> LogicManager : result
deactivate TimetableDateCommand
TimetableDateCommand -[hidden]-> LogicManager : result
destroy TimetableDateCommand

[<--LogicManager
deactivate LogicManager
@enduml
