@startuml

start
:User is in MAIN_MODE;
:User inputs 'review DECK_INDEX';
if () then ([Valid DECK_INDEX and deck is not empty])
    :User successfully enters REVIEW_MODE;
    repeat
        :Display the current card;
        :User attempts the question
        on the current card;
        :User inputs 'p' to flip the current
        card and see the answer;
        switch ()
        case ([card is easy])
        :User inputs 'l' to tag
        current card as easy;
        case ([card is medium])
        :User inputs ';' to tag
        current card as medium;
        case ([card is hard])
        :User inputs ''' to tag
        current card as hard;
        endswitch

        :User inputs ']' command to move on to next card;

    repeat while () is ([Next card exists])
    -> [Current card was last card];

    :Inform user that this was the last card;

    :User inputs 'endReview' command to return to MAIN_MODE;

else ([else])
    :Throw exception;
    :Display error message;

endif

:User is in MAIN_MODE;

stop
@enduml
