@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{

Class CompleteWindow
Class UnscheduledDeliveryJobListPanel
Class DeliveryJobCard

}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class TimetableWindow
TimetableWindow *-down-> "1" CompleteWindow
CompleteWindow --> Logic


CompleteWindow *-down-> "1" UnscheduledDeliveryJobListPanel
UnscheduledDeliveryJobListPanel *-down-> "*" DeliveryJobCard
@enduml
