@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class StatusBarFooter
Class ResultDisplay
Class CommandBox
Class HelpWindow
together {
Class CustomerListPanel
Class OrderListPanel
Class CustomerCard
Class OrderCard
}
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down-> "1" StatusBarFooter
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down->  "1" CommandBox
MainWindow -down-> "0..1" HelpWindow
MainWindow *-down-> "1" CustomerListPanel
MainWindow *-down-> "1" OrderListPanel
CustomerListPanel -down-> "*" CustomerCard
OrderListPanel -down-> "*" OrderCard

MainWindow -l-|> UiPart
StatusBarFooter --|> UiPart
ResultDisplay --|> UiPart
CommandBox --|> UiPart
HelpWindow --|> UiPart
CustomerListPanel --|> UiPart
OrderListPanel --|> UiPart
CustomerCard --|> UiPart
OrderCard --|> UiPart

CustomerCard ..> Model
OrderCard ..> Model
UiManager -right-> Logic
MainWindow -right-> Logic

OrderListPanel -[hidden]right- CustomerListPanel
CustomerListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
