@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
together {
    Class MainWindow
    Class LoginWindow
}
together {
    Class HelpWindow
    Class ResultDisplay
    Class PersonListPanel
    Class PersonCard
    Class StatusBarFooter
    Class CommandBox
}
Class WelcomeSection
Class LoadingSection
Class CreatePasswordSection
Class DefaultLoginSection
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .up.|> Ui
UiManager -right-> "1" MainWindow
UiManager -down-> "1" LoginWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" PersonListPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow --> "0..1" HelpWindow

LoginWindow *-down-> "1" WelcomeSection
LoginWindow *-down-> "1" LoadingSection
LoginWindow *-down-> "1" CreatePasswordSection
LoginWindow *-down-> "1" DefaultLoginSection

WelcomeSection --|> UiPart
LoadingSection --|> UiPart
CreatePasswordSection --|> UiPart
DefaultLoginSection --|> UiPart


PersonListPanel -down-> "*" PersonCard

MainWindow -left-|> UiPart
LoginWindow -down-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
PersonListPanel --|> UiPart
PersonCard --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart

PersonCard ..> Model
UiManager -right-> Logic
MainWindow -right-> Logic
LoginWindow -right-> Logic

PersonListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
