@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class XYZListPanel
Class XYZCard
Class StatusBarFooter
Class CommandBox
Class ListType
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> XYZListPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow --> "0..1" HelpWindow
MainWindow *-down-> "1" ListType
XYZListPanel -down-> "*" XYZCard
note right of XYZListPanel: XYZListPanel = ClientListPanel, \nProjectListPanel, etc.
note right of XYZCard: XYZCard = ClientCard, \nProjectCard, etc.

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
XYZListPanel --|> UiPart
XYZCard --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart

XYZCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

XYZListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
