@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow

Class DetailedInfoSection
Class DetailedContent
Class HeaderBar

Class GeneralExamsContent
Class FilledExamsContent
Class PastExamsListPanel
Class UpcomingExamsListPanel
Class ExamCard
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui


UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down-> "1" DetailedInfoSection
DetailedInfoSection *-down-> "1" HeaderBar
DetailedInfoSection *-down-> "1" DetailedContent
FilledExamsContent *-down-> "1" PastExamsListPanel
FilledExamsContent *-down-> "1" UpcomingExamsListPanel
PastExamsListPanel -down-> "*" ExamCard
UpcomingExamsListPanel -down-> "*" ExamCard

MainWindow -left-|> UiPart
DetailedInfoSection --|> UiPart
HeaderBar --|> UiPart
DetailedContent --|> UiPart
PastExamsListPanel --|> UiPart
UpcomingExamsListPanel --|> UiPart
ExamCard --|> UiPart

DetailedInfoSection ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic
GeneralExamsContent -up-|> DetailedContent
FilledExamsContent -up-|> GeneralExamsContent

MainWindow -[hidden]-|> UiPart
@enduml
