@startuml UiResultDisplayObjectDiagram
!include style.puml

skinparam RoundCorner 0
skinparam arrowThickness 1.1

Class "<u>:ResultDisplay</u>" as ResultDisplay UI_COLOR {
    -messageQueue: LinkedBlockingDeque<CommandMessage>
}
show ResultDisplay fields

Class "<u>:LogicManager</u>" as LogicManager LOGIC_COLOR
Class "<u>completionHandler:Consumer</u>" as Consumer LOGIC_COLOR

LogicManager -down-> Consumer
Consumer -down-> ResultDisplay : queues messages >

@enduml
