@startuml
!pragma layout smetana
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_DARK
skinparam classBackgroundColor UI_COLOR

package guihandles <<Rectangle>> UI_COLOR_BACKGROUND {
}

Class "{abstract}\nGuiUnitTest" as GuiUnitTest

AllUiTests -left-> guihandles
AllUiTests -|> GuiUnitTest
GuiUnitTest -down->"1  " GuiRobot
GuiRobot -|> FxRobot

@enduml
