@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":UnassignCommandParser" as UnassignCommandParser LOGIC_COLOR
participant "u:UnassignCommand" as UnassignCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box OfficeConnectModel MODEL_COLOR_T1
participant ":OfficeConnectModel" as OfficeConnectModel MODEL_COLOR
end box

[-> LogicManager : execute(commandText)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(userInput)
activate AddressBookParser

create UnassignCommandParser
AddressBookParser -> UnassignCommandParser
activate UnassignCommandParser

UnassignCommandParser --> AddressBookParser
deactivate UnassignCommandParser

AddressBookParser -> UnassignCommandParser : parse(args)
activate UnassignCommandParser

create UnassignCommand
UnassignCommandParser -> UnassignCommand
activate UnassignCommand

UnassignCommand --> UnassignCommandParser : u
deactivate UnassignCommand

UnassignCommandParser --> AddressBookParser : u


deactivate UnassignCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
UnassignCommandParser -[hidden]-> AddressBookParser
destroy UnassignCommandParser

AddressBookParser --> LogicManager : u
deactivate AddressBookParser

LogicManager -> UnassignCommand : execute(model, officeConnectModel)
activate UnassignCommand

UnassignCommand -> OfficeConnectModel : deleteAssignment(personToUnassign, taskToUnassign)
activate OfficeConnectModel

OfficeConnectModel --> UnassignCommand
deactivate OfficeConnectModel

create CommandResult
UnassignCommand -> CommandResult
activate CommandResult

CommandResult --> UnassignCommand
deactivate CommandResult

UnassignCommand --> LogicManager : CommandResult(MESSAGE_SUCCESS)
deactivate UnassignCommand

[<--LogicManager
deactivate LogicManager
@enduml
