@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "undo"

package States <<rectangle>> {
    class State1 as "ab0:DengueHotspotTracker"
    class State2 as "ab1:DengueHotspotTracker"
    class State3 as "ab2:DengueHotspotTracker"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "Current State" #8980FE

Pointer -up-> State2
@end
