@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CodocParser" as CodocParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedCodoc" as VersionedCodoc MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> CodocParser : parseCommand(undo)
activate CodocParser

create UndoCommand
CodocParser -> UndoCommand
activate UndoCommand

UndoCommand --> CodocParser
deactivate UndoCommand

CodocParser --> LogicManager : u
deactivate CodocParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoCodoc()
activate Model

Model -> VersionedCodoc : undo()
activate VersionedCodoc

VersionedCodoc -> VersionedCodoc :resetData(ReadOnlyCodoc)
VersionedCodoc --> Model :
deactivate VersionedCodoc

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
