@startuml
'https://plantuml.com/activity-diagram-beta

start
:User executes undo n;
if () then ([n contains non-digits \nother than whitespaes)])
    :display an invalid message;
    stop
else ([else])
    if () then ([n is not an empty string or whitespace])
        :argument is n;
    else ([else])
        :argument is 1;
    endif
    if () then ([can undo])
        :undo once;
        if () then ([enough undos available])
        :undo argument number of times;
        else ([else])
        :undo as many times possible (0 inclusive);
        endif
        stop
    else ([else])
        :display an invalid message;
        stop


@enduml
