@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #fefece
skinparam NoteBackgroundColor #yellow

title After command "clear"

package States <<rectangle>> {
    class State1 as "__ab0:AddressBook__"
    class State2 as "__ab3:AddressBook__"
    class State3 as "__ab2:AddressBook__"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3
hide State3

class Pointer as "Current State" #FFFFFF

Pointer -up[#a80036]-> State2
note right on link: Both states ab1 and ab2 are deleted.
@end
