@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "delete 5"

package States <<rectangle>> {
    class State1 as "__cd0:Codoc__" #FFFF99
    class State2 as "__cd1:Codoc__" #FFFF99
    class State3 as "__cd2:Codoc__" #FFFF99
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

hide State3

class Pointer as "Current State" #FFFFFF

Pointer -up-> State2
@end
