@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ElisterParser" as ElisterParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
participant "hist:StateHistory" as StateHistory MODEL_COLOR
participant "prev:Model" as PreviousModel MODEL_COLOR
end box
[-> LogicManager : execute(undo 5)
activate LogicManager

LogicManager -> ElisterParser : parseCommand(undo 5)
activate ElisterParser

create UndoCommand
ElisterParser -> UndoCommand
activate UndoCommand

UndoCommand --> ElisterParser
deactivate UndoCommand

ElisterParser --> LogicManager : u
deactivate ElisterParser

LogicManager -> UndoCommand : setHistory(hist)

LogicManager -> UndoCommand : execute(m)
activate UndoCommand

UndoCommand -> StateHistory : undo(5)

UndoCommand -> StateHistory : presentModel()
activate StateHistory

create PreviousModel
StateHistory -> PreviousModel
activate PreviousModel

PreviousModel --> StateHistory
deactivate PreviousModel

StateHistory --> UndoCommand : prev
deactivate StateHistory

UndoCommand -> PreviousModel : getElister()
activate PreviousModel

PreviousModel --> UndoCommand : ab
deactivate PreviousModel

UndoCommand -> Model : setElister(ab)
activate Model

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand

UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand
destroy PreviousModel

[<--LogicManager
deactivate LogicManager
@enduml
