@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "add_task n/Sort Storage d/01/01/2024"

package States <<rectangle>> {
    class State1 as "__t0:Trackr__" STATE_COLOR
    class State2 as "__t1:Trackr__" STATE_COLOR
    class State3 as "__t2:Trackr__" STATE_COLOR
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "Current State"

Pointer -up-> State3
@end
