@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Initial state

package States {
    class State1 as "<u>b0:InternshipBook"
    class State2 as "<u>b1:InternshipBook"
    class State3 as "<u>b2:InternshipBook"
}
State1 -[hidden]right-> State2
State2 -[hidden]right-> State3
hide State2
hide State3

class Pointer as "Current State" #FFFFDD\9
Pointer -up-> State1
@end
