@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":PetPalParser" as PetPalParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":PetPal" as PetPal MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> PetPalParser : parseCommand(undo)
activate PetPalParser

create UndoCommand
PetPalParser -> UndoCommand
activate UndoCommand

UndoCommand -->PetPalParser
deactivate UndoCommand

PetPalParser --> LogicManager : u
deactivate PetPalParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undo()
activate Model

Model -> PetPal : undo()
activate PetPal

PetPal -> PetPal :new PetPal(ReadOnlyPetPal)
PetPal --> Model :
deactivate PetPal

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
