@startuml
'https://plantuml.com/class-diagram

start
:User enters an untag command;

if () then ([No tags are removed])
    :Error: No Tags;

elseif () then ([Group and Module Tags are removed])
    :Error: Both Tags;

else ()
:Removes tags if exist;
endif
stop
@enduml
