@startuml
!include style.puml

Actor User as user USER_COLOR
box Ui UI_COLOR_T0
Participant ":DoctorListViewCell" as doctorListViewCell UI_COLOR
Participant ":ContactDisplay" as contactDisplay MODEL_COLOR
Participant ":EnlargedDoctorInfoCard" as enlargedDoctorInfoCard LOGIC_COLOR_T2
Participant ":StackPane" as enlargedPersonInfoCardPlaceholder STORAGE_COLOR
end box

user -[USER_COLOR]> doctorListViewCell : MOUSE_CLICKED
activate doctorListViewCell UI_COLOR

doctorListViewCell -[UI_COLOR]> contactDisplay : setFeedbackUponSelectingDoctor(doctor)
activate contactDisplay MODEL_COLOR

contactDisplay -[MODEL_COLOR]> enlargedDoctorInfoCard : updateSelectedDoctor(doctor)
activate enlargedDoctorInfoCard LOGIC_COLOR_T2

enlargedDoctorInfoCard --[LOGIC_COLOR_T2]> contactDisplay
deactivate enlargedDoctorInfoCard LOGIC_COLOR_T2

contactDisplay -[MODEL_COLOR]> enlargedPersonInfoCardPlaceholder : clear children nodes
activate enlargedPersonInfoCardPlaceholder STORAGE_COLOR

enlargedPersonInfoCardPlaceholder --[STORAGE_COLOR]> contactDisplay
deactivate enlargedPersonInfoCardPlaceholder STORAGE_COLOR

contactDisplay -[MODEL_COLOR]> enlargedPersonInfoCardPlaceholder : add EnlargedDoctorInfoCard as child node
activate enlargedPersonInfoCardPlaceholder STORAGE_COLOR

enlargedPersonInfoCardPlaceholder --[STORAGE_COLOR]> contactDisplay
deactivate enlargedPersonInfoCardPlaceholder STORAGE_COLOR

contactDisplay --[MODEL_COLOR]> doctorListViewCell : setFeedbackUponSelectingDoctor(doctor)
deactivate contactDisplay MODEL_COLOR

doctorListViewCell--[UI_COLOR]> user
deactivate doctorListViewCell
@enduml
