@startuml
!include style.puml
skinparam dpi 200

Actor User as user USER_COLOR
box Ui UI_COLOR_T0
Participant ":DoctorListViewCell" as doctorListViewCell UI_COLOR
Participant ":ContactDisplay" as contactDisplay UI_COLOR
Participant ":EnlargedDoctorInfoCard" as enlargedDoctorInfoCard UI_COLOR
Participant "enlargedInfoCardPlaceholder:StackPane" as enlargedPersonInfoCardPlaceholder UI_COLOR
end box

user -[USER_COLOR]> doctorListViewCell : MOUSE_CLICKED
activate doctorListViewCell UI_COLOR

doctorListViewCell -[UI_COLOR]> contactDisplay : setFeedbackUponSelectingDoctor(doctor)
activate contactDisplay UI_COLOR

contactDisplay -[UI_COLOR]> enlargedDoctorInfoCard : updateSelectedDoctor(doctor)
activate enlargedDoctorInfoCard UI_COLOR

enlargedDoctorInfoCard --[UI_COLOR]> contactDisplay
deactivate enlargedDoctorInfoCard UI_COLOR

contactDisplay -[UI_COLOR]> enlargedPersonInfoCardPlaceholder : clear children nodes
activate enlargedPersonInfoCardPlaceholder UI_COLOR

enlargedPersonInfoCardPlaceholder --[UI_COLOR]> contactDisplay
deactivate enlargedPersonInfoCardPlaceholder UI_COLOR

contactDisplay -[UI_COLOR]> enlargedPersonInfoCardPlaceholder : add EnlargedDoctorInfoCard as child node
activate enlargedPersonInfoCardPlaceholder UI_COLOR

enlargedPersonInfoCardPlaceholder --[UI_COLOR]> contactDisplay
deactivate enlargedPersonInfoCardPlaceholder UI_COLOR

contactDisplay --[UI_COLOR]> doctorListViewCell : setFeedbackUponSelectingDoctor(doctor)
deactivate contactDisplay UI_COLOR

doctorListViewCell--[UI_COLOR]> user
deactivate doctorListViewCell
@enduml
