@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ViewCustomerCommandParser" as ViewCustomerCommandParser LOGIC_COLOR
participant "v:ViewCustomerCommand" as ViewCustomerCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("viewcustomer 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("viewcustomer 1")
activate AddressBookParser

create ViewCustomerCommandParser
AddressBookParser -> ViewCustomerCommandParser
activate ViewCustomerCommandParser

ViewCustomerCommandParser --> AddressBookParser
deactivate ViewCustomerCommandParser

AddressBookParser -> ViewCustomerCommandParser : parse("1")
activate ViewCustomerCommandParser

create ViewCustomerCommand
ViewCustomerCommandParser -> ViewCustomerCommand
activate ViewCustomerCommand

ViewCustomerCommand --> ViewCustomerCommandParser : v
deactivate ViewCustomerCommand

ViewCustomerCommandParser --> AddressBookParser : v
deactivate ViewCustomerCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ViewCustomerCommandParser -[hidden]-> AddressBookParser
destroy ViewCustomerCommandParser

AddressBookParser --> LogicManager : v
deactivate AddressBookParser

LogicManager -> ViewCustomerCommand : execute()
activate ViewCustomerCommand

ViewCustomerCommand -> Model : updateFilteredAppointmentList(predicate)
activate Model

Model --> ViewCustomerCommand
deactivate Model

create CommandResult
ViewCustomerCommand -> CommandResult
activate CommandResult

CommandResult --> ViewCustomerCommand
deactivate CommandResult

ViewCustomerCommand --> LogicManager : result
deactivate ViewCustomerCommand

[<--LogicManager
deactivate LogicManager
@enduml
