@startuml
start
:User enters view command
with optional arguments;
if () then ([contact index present])
    : Find Person in Model;
    if () then ([Person exists])
    : Retrieve Person
        from Model;
    else ([else])
    : No Person Found
        feedback to User;
        stop;
    endif
elseif () then ([has Name argument])
    : Find Person in Model;
    if () then ([Person exists])
    : Retrieve Person
        from Model;
    else ([else])
    : Retrieve User
       from Model;
    endif
else ([else])
    :Retrieve User
     from Model;
endif
:Person appears on view window;
stop
@enduml
