@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([in Edit Mode])
    :command to EditModeParser;
    if() then ([field "b" / "back"])
    -exit Edit Mode
    else ([else])
    -edit Entity according to <FIELD> <VALUE> syntax
    endif
else ([else])
    -command to AddressBookParser
    -parsed according to Command Words
endif
stop
@enduml
