@startuml  EditExpenseFindPartSequenceDiagram
!include ../../style.puml

hide footbox
skinparam MinClassWidth 50
skinparam ParticipantPadding 10
skinparam Shadowing false
skinparam DefaultTextAlignment center
skinparam packageStyle Rectangle

box Logic LOGIC_COLOR_T1
participant ":EditExpenseCommand" as Command  order 1 LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "category: Category" as Category order 2 MODEL_COLOR
end box

loop until matching category is found
    create Category
    Command -> Category
    activate Category
    Category -[hidden]> Command
    deactivate Category

    Command-[hidden]->Category
     activate Category
    Category -> Category :equals(newExpenseCategoryInString)
    opt if equals check is true
       Category -[hidden]> Category
       Category --> Command
    end
    deactivate Category
end
@enduml
