@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Find {
Class FindCommandParser
Class "<<interface>> \n Predicate"
Class XYZPredicate
Class FindCommand
}

XYZPredicate .up|> "<<interface>> \n Predicate"
FindCommand .> XYZPredicate : Filter with >
FindCommandParser .down> XYZPredicate : Creates >
FindCommandParser .down> FindCommand : Creates >
"<<interface>> \n Predicate" -[hidden]down- FindCommand

note right of XYZPredicate: XYZPredicate = \nAddressContainsKeywordPredicate, \nRiskLevelIsEqualPredicate, etc

@enduml
