@startuml
hide footbox

!define LOGIC_COLOR #3333C4
!define LOGIC_COLOR_T1 #7777DB
!define LOGIC_COLOR_T2 #5252CE
!define LOGIC_COLOR_T3 #1616B0
!define LOGIC_COLOR_T4 #101086
!define MODEL_COLOR #C43333
!define MODEL_COLOR_T1 #DB7777

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":DengueHotspotTrackerParser" as DengueHotspotTrackerParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant ":DeleteCommand" as DeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1 3")
activate LogicManager

LogicManager -> DengueHotspotTrackerParser : parseCommand("delete 1 3")
activate DengueHotspotTrackerParser

create DeleteCommandParser
DengueHotspotTrackerParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> DengueHotspotTrackerParser
deactivate DeleteCommandParser

DengueHotspotTrackerParser -> DeleteCommandParser : parse("1 3")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : List<Index>
deactivate DeleteCommand

DeleteCommandParser --> DengueHotspotTrackerParser : List<Index>
deactivate DeleteCommandParser

DengueHotspotTrackerParser --> LogicManager : List<Index>
deactivate DengueHotspotTrackerParser

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

loop size of List<Index>
DeleteCommand -> Model : deletePerson(index)
activate Model

Model --> DeleteCommand
deactivate Model
end

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand

LogicManager -->[
deactivate LogicManager

@enduml
