package seedu.address.model.util;

import java.util.Arrays;
import java.util.Set;
import java.util.stream.Collectors;

import seedu.address.model.AddressBook;
import seedu.address.model.ReadOnlyAddressBook;
import seedu.address.model.person.Address;
import seedu.address.model.person.Email;
import seedu.address.model.person.Name;
import seedu.address.model.person.Person;
import seedu.address.model.person.Phone;
import seedu.address.model.tag.Tag;

/**
 * Contains utility methods for populating {@code AddressBook} with sample data.
 */
public class SampleDataUtil {
    public static Person getSampleUser() {
        return new Person(new Name("Linus Richards"),
                new Phone("90102030"),
                new Email("linusrichards@gmail.com"),
                new Address("National University of Singapore"),
                getTagSet());
    }

    public static Person[] getSamplePersons() {
        return new Person[] {
            new Person(new Name("Syed Alwi Mustafa"),
                    new Phone("83107473"),
                    new Email("syedalwimustafa@gmail.com"),
                    new Address("Mustafa Centre"),
                    getTagSet("UpperThomson", "Enemy")),
            new Person(new Name("Nicholas Tan Bin"),
                    new Phone("83831575"),
                    new Email("nicholastanbin@gmail.com"),
                    new Address("20 Tampines Central 1"),
                    getTagSet("Tampines", "TA", "Groupmate")),
            new Person(new Name("Soo Teck"),
                    new Phone("83231087"),
                    new Email("sooteck@gmail.com"),
                    new Address("21 Punggol Way"),
                    getTagSet("SooTeck")),
            new Person(new Name("Benjamin DeMeer"),
                    new Phone("83279539"),
                    new Email("benjamindemeer@gmail.com"),
                    new Address("11 Kallang Bahru"),
                    getTagSet("Bendemeer", "TA")),
            new Person(new Name("Yew Tee"),
                    new Phone("83338709"),
                    new Email("yewtee@gmail.com"),
                    new Address("61 Choa Chu Kang Drive"),
                    getTagSet("YewTee", "NS")),
            new Person(new Name("Clark Kee"),
                    new Phone("83476489"),
                    new Email("clarkkee@gmail.com"),
                    new Address("10 Eu Tong Sen Street"),
                    getTagSet("ClarkeQuay", "NUS")),
            new Person(new Name("Robin Stevens"),
                    new Phone("83538089"),
                    new Email("robinstevens@gmail.com"),
                    new Address("92 Stevens Road"),
                    getTagSet("Stevens", "TA", "Study")),
            new Person(new Name("Granger Summers"),
                    new Phone("83862251"),
                    new Email("grangersummers@gmail.com"),
                    new Address("1 Somerset Road"),
                    getTagSet("Somerset", "NS")),
            new Person(new Name("Dawson Quentin"),
                    new Phone("84087052"),
                    new Email("dawsonquentin@gmail.com"),
                    new Address("301 Commonwealth Avenue"),
                    getTagSet("Queenstown", "Groupmate")),
            new Person(new Name("Choa Chu Kang"),
                    new Phone("81480078"),
                    new Email("choachukang@gmail.com"),
                    new Address("10 Choa Chu Kang Avenue 4"),
                    getTagSet("ChoaChuKang", "JC", "JC", "NS")),
            new Person(new Name("Hong Shan"),
                    new Phone("81567887"),
                    new Email("hongshan@gmail.com"),
                    new Address("920 Tiong Bahru Road"),
                    getTagSet("Redhill", "Groupmate")),
            new Person(new Name("Marina Wan"),
                    new Phone("81604546"),
                    new Email("marinawan@gmail.com"),
                    new Address("Marina One"),
                    getTagSet("UpperThomson", "Enemy")),
            new Person(new Name("Low Wong Chuan"),
                    new Phone("82722177"),
                    new Email("lowwongchuan@gmail.com"),
                    new Address("150 Serangoon Avenue 3"),
                    getTagSet("LorongChuan", "CCA")),
            new Person(new Name("Nurul Khatibah Abdul Ibrahim"),
                    new Phone("84123469"),
                    new Email("nurulkhatibahabdulibrahim@gmail.com"),
                    new Address("201 Yishun Avenue 2"),
                    getTagSet("Khatib", "NS")),
            new Person(new Name("Yio Chu Kang"),
                    new Phone("84377174"),
                    new Email("yiochukang@gmail.com"),
                    new Address("3000 Ang Mo Kio Avenue 8"),
                    getTagSet("YioChuKang", "NS")),
            new Person(new Name("Sim Ga Rang"),
                    new Phone("84453853"),
                    new Email("simgarang@gmail.com"),
                    new Address("5 Sims Avenue"),
                    getTagSet("Kallang", "Groupmate")),
            new Person(new Name("Albert Blackmore"),
                    new Phone("84456862"),
                    new Email("albertblackmore@gmail.com"),
                    new Address("2 Blackmore Drive"),
                    getTagSet("KingAlbertPark", "TA")),
            new Person(new Name("Yunus Abdul Razak"),
                    new Phone("84828836"),
                    new Email("yunusabdulrazak@gmail.com"),
                    new Address("30 Eunos Crescent"),
                    getTagSet("Eunos", "Groupmate")),
            new Person(new Name("San Gi Chim"),
                    new Phone("84834901"),
                    new Email("sangichim@gmail.com"),
                    new Address("10 Bukit Batok Central"),
                    getTagSet("BukitBatok", "NS")),
            new Person(new Name("Bee Shan"),
                    new Phone("84860751"),
                    new Email("beeshan@gmail.com"),
                    new Address("200 Bishan Road"),
                    getTagSet("Bishan", "CCA", "NS")),
            new Person(new Name("Juan Fullerton"),
                    new Phone("85006974"),
                    new Email("juanfullerton@gmail.com"),
                    new Address("One Fullerton"),
                    getTagSet("UpperThomson", "Enemy")),
            new Person(new Name("Maxwell Neal"),
                    new Phone("85017099"),
                    new Email("maxwellneal@gmail.com"),
                    new Address("50 Neil Road"),
                    getTagSet("Maxwell", "Study")),
            new Person(new Name("Nee Soon"),
                    new Phone("85254526"),
                    new Email("neesoon@gmail.com"),
                    new Address("301 Yishun Avenue 2"),
                    getTagSet("Yishun", "NS")),
            new Person(new Name("Wen Qing"),
                    new Phone("85482741"),
                    new Email("wenqing@gmail.com"),
                    new Address("900 Serangoon Road"),
                    getTagSet("BoonKeng", "NUS")),
            new Person(new Name("Khoo Pang"),
                    new Phone("85538631"),
                    new Email("khoopang@gmail.com"),
                    new Address("60 Fernvale Street"),
                    getTagSet("Kupang")),
            new Person(new Name("Wisteria Chung"),
                    new Phone("85934557"),
                    new Email("wisteriachung@gmail.com"),
                    new Address("Wisteria Mall"),
                    getTagSet("UpperThomson", "Enemy")),
            new Person(new Name("Nicole Hai Wei Ting"),
                    new Phone("86222187"),
                    new Email("nicolehaiweiting@gmail.com"),
                    new Address("20 Republic Avenue"),
                    getTagSet("NicollHighway", "CCA")),
            new Person(new Name("Tan Kah Kee"),
                    new Phone("86247441"),
                    new Email("tankahkee@gmail.com"),
                    new Address("651 Bukit Timah Road"),
                    getTagSet("TanKahKee", "TA")),
            new Person(new Name("May See"),
                    new Phone("86407466"),
                    new Email("maysee@gmail.com"),
                    new Address("30 Simei Street 3"),
                    getTagSet("Simei", "Groupmate")),
            new Person(new Name("George Richards"),
                    new Phone("86437383"),
                    new Email("georgerichards@gmail.com"),
                    new Address("301 South Buona Vista Road"),
                    getTagSet("KentRidge", "CCA")),
            new Person(new Name("Ewan MacPherson"),
                    new Phone("86500072"),
                    new Email("ewanmacpherson@gmail.com"),
                    new Address("171 Paya Lebar Road"),
                    getTagSet("MacPherson", "CCA", "TA")),
            new Person(new Name("Dong Yu Lang"),
                    new Phone("86691000"),
                    new Email("dongyulang@gmail.com"),
                    new Address("10 Jurong East Street 12"),
                    getTagSet("JurongEast", "NS")),
            new Person(new Name("Joo Koon"),
                    new Phone("86716401"),
                    new Email("jookoon@gmail.com"),
                    new Address("91 Joo Koon Circle"),
                    getTagSet("JooKoon", "Groupmate")),
            new Person(new Name("Leedon Holland"),
                    new Phone("86819421"),
                    new Email("leedonholland@gmail.com"),
                    new Address("200 Holland Avenue"),
                    getTagSet("HollandVillage", "CCA")),
            new Person(new Name("Dakota Windsor"),
                    new Phone("86995979"),
                    new Email("dakotawindsor@gmail.com"),
                    new Address("201 Old Airport Road"),
                    getTagSet("Dakota", "CCA")),
            new Person(new Name("Ferra Park"),
                    new Phone("87295338"),
                    new Email("ferrapark@gmail.com"),
                    new Address("250 Race Course Road"),
                    getTagSet("FarrerPark", "NUS")),
            new Person(new Name("Alex Quentin"),
                    new Phone("87297381"),
                    new Email("alexquentin@gmail.com"),
                    new Address("301 Commonwealth Avenue"),
                    getTagSet("Queenstown", "Groupmate")),
            new Person(new Name("Ford Canning"),
                    new Phone("87709745"),
                    new Email("fordcanning@gmail.com"),
                    new Address("170 River Valley Road"),
                    getTagSet("FortCanning", "TA")),
            new Person(new Name("Mary Caldecott"),
                    new Phone("87713410"),
                    new Email("marycaldecott@gmail.com"),
                    new Address("38 Toa Payoh Rise"),
                    getTagSet("Caldecott", "CCA", "Study")),
            new Person(new Name("Illyas Alhaq"),
                    new Phone("88273317"),
                    new Email("illyasalhaq@gmail.com"),
                    new Address("Elias Mall"),
                    getTagSet("UpperThomson", "Enemy")),
            new Person(new Name("Shun Yi"),
                    new Phone("88285486"),
                    new Email("shunyi@gmail.com"),
                    new Address("301 Yishun Avenue 2"),
                    getTagSet("Yishun", "NS")),
            new Person(new Name("Sallim Mattar"),
                    new Phone("88378162"),
                    new Email("sallimmattar@gmail.com"),
                    new Address("60 Merpati Road"),
                    getTagSet("Mattar", "TA")),
            new Person(new Name("Chun Ye"),
                    new Phone("88443214"),
                    new Email("chunye@gmail.com"),
                    new Address("825 Upper Thomson Road"),
                    getTagSet("Springleaf", "Study")),
            new Person(new Name("Mary Meng"),
                    new Phone("88712151"),
                    new Email("marymeng@gmail.com"),
                    new Address("60 Marymount Road"),
                    getTagSet("Marymount", "CCA")),
            new Person(new Name("Maya Takashi"),
                    new Phone("88714338"),
                    new Email("mayatakashi@gmail.com"),
                    new Address("Ngee Ann City"),
                    getTagSet("UpperThomson", "Enemy")),
            new Person(new Name("Clement Tee"),
                    new Phone("88839880"),
                    new Email("clementtee@gmail.com"),
                    new Address("3150 Commonwealth Avenue West"),
                    getTagSet("Clementi", "Groupmate")),
            new Person(new Name("Nicole Windsor"),
                    new Phone("89304957"),
                    new Email("nicolewindsor@gmail.com"),
                    new Address("20 Republic Avenue"),
                    getTagSet("NicollHighway", "CCA")),
            new Person(new Name("Tim Holland"),
                    new Phone("89352093"),
                    new Email("timholland@gmail.com"),
                    new Address("200 Holland Avenue"),
                    getTagSet("HollandVillage", "CCA")),
            new Person(new Name("Nicole Tan Bin"),
                    new Phone("89594917"),
                    new Email("nicoletanbin@gmail.com"),
                    new Address("20 Tampines Central 1"),
                    getTagSet("Tampines", "TA", "Groupmate")),
            new Person(new Name("Victoria Raffles"),
                    new Phone("89682744"),
                    new Email("victoriaraffles@gmail.com"),
                    new Address("5 Raffles Place"),
                    getTagSet("RafflesPlace", "Groupmate", "NS")),
            new Person(new Name("Lavender Crawford"),
                    new Phone("91240480"),
                    new Email("lavendercrawford@gmail.com"),
                    new Address("50 Kallang Road"),
                    getTagSet("Lavender", "Groupmate")),
            new Person(new Name("Ang Djit Sun"),
                    new Phone("91534639"),
                    new Email("angdjitsun@gmail.com"),
                    new Address("2450 Ang Mo Kio Avenue 8"),
                    getTagSet("AngMoKio", "NS")),
            new Person(new Name("Wen Li"),
                    new Phone("91692604"),
                    new Email("wenli@gmail.com"),
                    new Address("301 Boon Lay Way"),
                    getTagSet("BoonLay", "Groupmate", "JC")),
            new Person(new Name("Scott Newton"),
                    new Phone("92099660"),
                    new Email("scottnewton@gmail.com"),
                    new Address("49 Scotts Road"),
                    getTagSet("Newton", "TA", "NS")),
            new Person(new Name("Keat Hong"),
                    new Phone("92450533"),
                    new Email("keathong@gmail.com"),
                    new Address("30 Choa Chu Kang Way"),
                    getTagSet("KeatHong", "JC")),
            new Person(new Name("Vernon Lee"),
                    new Phone("92968220"),
                    new Email("vernonlee@gmail.com"),
                    new Address("90 Bartley Road"),
                    getTagSet("Bartley", "CCA")),
            new Person(new Name("Jing Kai Xiu"),
                    new Phone("92968348"),
                    new Email("jingkaixiu@gmail.com"),
                    new Address("1 Cashew Road"),
                    getTagSet("Cashew", "TA")),
            new Person(new Name("Wang Kok"),
                    new Phone("93135199"),
                    new Email("wangkok@gmail.com"),
                    new Address("10 Sengkang Central"),
                    getTagSet("Buangkok", "NUS")),
            new Person(new Name("Teck Lee"),
                    new Phone("93535285"),
                    new Email("tecklee@gmail.com"),
                    new Address("101 Ponggol Seventeenth Avenue"),
                    getTagSet("TeckLee")),
            new Person(new Name("Jubilee Ang"),
                    new Phone("93630719"),
                    new Email("jubileeang@gmail.com"),
                    new Address("2450 Ang Mo Kio Avenue 8"),
                    getTagSet("AngMoKio", "NS")),
            new Person(new Name("Ang Mei Hua"),
                    new Phone("93770058"),
                    new Email("angmeihua@gmail.com"),
                    new Address("91 Ang Mo Kio Avenue 4"),
                    getTagSet("Mayflower", "Study")),
            new Person(new Name("Amirah Tan"),
                    new Phone("93819675"),
                    new Email("amirahtan@gmail.com"),
                    new Address("920 New Upper Changi Road"),
                    getTagSet("TanahMerah", "Groupmate")),
            new Person(new Name("Brad Toh"),
                    new Phone("93957105"),
                    new Email("bradtoh@gmail.com"),
                    new Address("377 Lorong 1 Toa Payoh"),
                    getTagSet("Braddell", "NS")),
            new Person(new Name("Zhang Yi"),
                    new Phone("94139782"),
                    new Email("zhangyi@gmail.com"),
                    new Address("Changi Airport"),
                    getTagSet("UpperThomson", "Enemy")),
            new Person(new Name("Sam Kee"),
                    new Phone("94212770"),
                    new Email("samkee@gmail.com"),
                    new Address("10 Sentul Crescent"),
                    getTagSet("SamKee")),
            new Person(new Name("Mary Thomson"),
                    new Phone("94547963"),
                    new Email("marythomson@gmail.com"),
                    new Address("60 Marymount Road"),
                    getTagSet("Marymount", "CCA")),
            new Person(new Name("Joo Rong"),
                    new Phone("94662261"),
                    new Email("joorong@gmail.com"),
                    new Address("10 Jurong East Street 12"),
                    getTagSet("JurongEast", "NS")),
            new Person(new Name("Bart Lee"),
                    new Phone("94724843"),
                    new Email("bartlee@gmail.com"),
                    new Address("90 Bartley Road"),
                    getTagSet("Bartley", "CCA")),
            new Person(new Name("Maxwell Smith"),
                    new Phone("94740890"),
                    new Email("maxwellsmith@gmail.com"),
                    new Address("50 Neil Road"),
                    getTagSet("Maxwell", "Study")),
            new Person(new Name("Thomas Nakayama"),
                    new Phone("94744364"),
                    new Email("thomasnakayama@gmail.com"),
                    new Address("Zhongshan Mall"),
                    getTagSet("UpperThomson", "Enemy")),
            new Person(new Name("Gwon Se Rang"),
                    new Phone("94755346"),
                    new Email("gwonserang@gmail.com"),
                    new Address("600 Upper Serangoon Road"),
                    getTagSet("Serangoon", "CCA", "NUS")),
            new Person(new Name("Teck Whye"),
                    new Phone("95061476"),
                    new Email("teckwhye@gmail.com"),
                    new Address("10 Choa Chu Kang Way"),
                    getTagSet("TeckWhye", "JC")),
            new Person(new Name("Soon Teck"),
                    new Phone("95368548"),
                    new Email("soonteck@gmail.com"),
                    new Address("Suntec City"),
                    getTagSet("UpperThomson", "Enemy")),
            new Person(new Name("Eusoff Richards"),
                    new Phone("95427585"),
                    new Email("eusoffrichards@gmail.com"),
                    new Address("301 South Buona Vista Road"),
                    getTagSet("KentRidge", "CCA")),
            new Person(new Name("Seth Summers"),
                    new Phone("95985025"),
                    new Email("sethsummers@gmail.com"),
                    new Address("1 Somerset Road"),
                    getTagSet("Somerset", "NS")),
            new Person(new Name("Melania Walker"),
                    new Phone("95990357"),
                    new Email("melaniawalker@gmail.com"),
                    new Address("Millenia Walk"),
                    getTagSet("UpperThomson", "Enemy")),
            new Person(new Name("Edward Richards"),
                    new Phone("96157147"),
                    new Email("edwardrichards@gmail.com"),
                    new Address("301 South Buona Vista Road"),
                    getTagSet("KentRidge", "CCA")),
            new Person(new Name("Ritchie Thomson"),
                    new Phone("96166852"),
                    new Email("ritchiethomson@gmail.com"),
                    new Address("1 Jalan Keli"),
                    getTagSet("UpperThomson", "Study")),
            new Person(new Name("Boon Kheng"),
                    new Phone("96281212"),
                    new Email("boonkheng@gmail.com"),
                    new Address("900 Serangoon Road"),
                    getTagSet("BoonKeng", "NUS")),
            new Person(new Name("Albert Park"),
                    new Phone("96337927"),
                    new Email("albertpark@gmail.com"),
                    new Address("2 Blackmore Drive"),
                    getTagSet("KingAlbertPark", "TA")),
            new Person(new Name("Edward Anson"),
                    new Phone("96396482"),
                    new Email("edwardanson@gmail.com"),
                    new Address("80 Shenton Way"),
                    getTagSet("PrinceEdwardRoad", "CCA")),
            new Person(new Name("Pearl Outram"),
                    new Phone("96482047"),
                    new Email("pearloutram@gmail.com"),
                    new Address("10 Outram Road"),
                    getTagSet("OutramPark", "Groupmate", "NUS", "Study")),
            new Person(new Name("Kent Richards"),
                    new Phone("97144842"),
                    new Email("kentrichards@gmail.com"),
                    new Address("301 South Buona Vista Road"),
                    getTagSet("KentRidge", "CCA")),
            new Person(new Name("Shannon Wei"),
                    new Phone("97216417"),
                    new Email("shannonwei@gmail.com"),
                    new Address("2 Park Street"),
                    getTagSet("ShentonWay", "Study")),
            new Person(new Name("Khadijah Al Junied"),
                    new Phone("97458132"),
                    new Email("khadijahaljunied@gmail.com"),
                    new Address("81 Lorong 25 Geylang"),
                    getTagSet("Aljunied", "Groupmate")),
            new Person(new Name("Steven Whitley"),
                    new Phone("97538209"),
                    new Email("stevenwhitley@gmail.com"),
                    new Address("92 Stevens Road"),
                    getTagSet("Stevens", "TA", "Study")),
            new Person(new Name("Glenn Napier"),
                    new Phone("98164980"),
                    new Email("glennnapier@gmail.com"),
                    new Address("2 Napier Road"),
                    getTagSet("Napier", "Study")),
            new Person(new Name("Marina Bay"),
                    new Phone("98318887"),
                    new Email("marinabay@gmail.com"),
                    new Address("21 Park Street"),
                    getTagSet("MarinaBay", "NS", "Study")),
            new Person(new Name("Novena Thomson"),
                    new Phone("98392692"),
                    new Email("novenathomson@gmail.com"),
                    new Address("250 Thomson Road"),
                    getTagSet("Novena", "NS")),
            new Person(new Name("Travis Scott"),
                    new Phone("98737469"),
                    new Email("travisscott@gmail.com"),
                    new Address("123456"),
                    getTagSet("Tavistock")),
            new Person(new Name("Cheng Lim"),
                    new Phone("98868145"),
                    new Email("chenglim@gmail.com"),
                    new Address("5 Anchorvale Street"),
                    getTagSet("ChengLim")),
            new Person(new Name("Charles Windsor"),
                    new Phone("98951626"),
                    new Email("charleswindsor@gmail.com"),
                    new Address("301 Mountbatten Road"),
                    getTagSet("Mountbatten", "CCA")),
            new Person(new Name("Kevin Ho"),
                    new Phone("99010658"),
                    new Email("kevinho@gmail.com"),
                    new Address("900 Upper Serangoon Road"),
                    getTagSet("Kovan", "NUS")),
            new Person(new Name("Ang Mo Kio"),
                    new Phone("99067341"),
                    new Email("angmokio@gmail.com"),
                    new Address("2450 Ang Mo Kio Avenue 8"),
                    getTagSet("AngMoKio", "NS")),
            new Person(new Name("Marcy Ling"),
                    new Phone("99375388"),
                    new Email("marcyling@gmail.com"),
                    new Address("71 Woodlands Avenue 3"),
                    getTagSet("Marsiling", "NS")),
            new Person(new Name("Komyo San"),
                    new Phone("99582126"),
                    new Email("komyosan@gmail.com"),
                    new Address("100 Sin Ming Avenue"),
                    getTagSet("BrightHill", "Study")),
            new Person(new Name("Steven Tan"),
                    new Phone("99583279"),
                    new Email("steventan@gmail.com"),
                    new Address("92 Stevens Road"),
                    getTagSet("Stevens", "TA", "Study")),
            new Person(new Name("Boon Lay"),
                    new Phone("99616982"),
                    new Email("boonlay@gmail.com"),
                    new Address("301 Boon Lay Way"),
                    getTagSet("BoonLay", "Groupmate", "JC")),
            new Person(new Name("Amirah Tee"),
                    new Phone("99691900"),
                    new Email("amirahtee@gmail.com"),
                    new Address("70 Woodlands Avenue 7"),
                    getTagSet("Admiralty", "NS")),
            new Person(new Name("Benjamin Coolen"),
                    new Phone("99906709"),
                    new Email("benjamincoolen@gmail.com"),
                    new Address("31 Bencoolen Street"),
                    getTagSet("Bencoolen", "TA"))
        };
    }

    public static ReadOnlyAddressBook getSampleAddressBook() {
        AddressBook sampleAb = new AddressBook();
        for (Person samplePerson : getSamplePersons()) {
            sampleAb.addPerson(samplePerson);
        }
        sampleAb.setUser(getSampleUser());
        return sampleAb;
    }

    /**
     * Returns a tag set containing the list of strings given.
     */
    public static Set<Tag> getTagSet(String... strings) {
        return Arrays.stream(strings)
                .map(Tag::new)
                .collect(Collectors.toSet());
    }

}
