package seedu.address.model.util;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;

import seedu.address.model.EduMate;
import seedu.address.model.ReadOnlyEduMate;
import seedu.address.model.person.Address;
import seedu.address.model.person.Email;
import seedu.address.model.person.Name;
import seedu.address.model.person.Person;
import seedu.address.model.person.Phone;
import seedu.address.model.person.TelegramHandle;
import seedu.address.model.person.User;
import seedu.address.model.tag.GroupTag;
import seedu.address.model.tag.ModuleTag;

/**
 * Contains utility methods for populating {@code EduMate} with sample data.
 */
public class SampleDataUtil {
    public static User getSampleUser() {
        return new User(new Name("Linus Richards"),
                new Phone("90102030"),
                new Email("linusrichards@gmail.com"),
                new Address("National University of Singapore"),
                new TelegramHandle("@linusrichards"),
                getGroupTagSet(),
                new HashSet<>() {{
                    add(new ModuleTag("CS2101"));
                    add(new ModuleTag("CS2102"));
                    add(new ModuleTag("CS2103T"));
                    add(new ModuleTag("CS2105"));
                    add(new ModuleTag("CS2106"));
                }});
    }

    public static Person[] getSamplePersons() {
        return new Person[] {
            new Person(new Name("Lavender Crawford"),
                    new Phone("81264774"),
                    new Email("lavendercrawford@gmail.com"),
                    new Address("50 Kallang Road"),
                    getGroupTagSet("Lavender", "Groupmate")),
            new Person(new Name("Nicole Tan Bin"),
                    new Phone("82041858"),
                    new Email("nicoletanbin@gmail.com"),
                    new Address("20 Tampines Central 1"),
                    getGroupTagSet("Tampines", "TA", "Groupmate")),
            new Person(new Name("San Gi Chim"),
                    new Phone("82288350"),
                    new Email("sangichim@gmail.com"),
                    new Address("10 Bukit Batok Central"),
                    getGroupTagSet("BukitBatok", "NS")),
            new Person(new Name("Joo Koon"),
                    new Phone("82723322"),
                    new Email("jookoon@gmail.com"),
                    new Address("91 Joo Koon Circle"),
                    getGroupTagSet("JooKoon", "Groupmate")),
            new Person(new Name("Keat Hong"),
                    new Phone("82822988"),
                    new Email("keathong@gmail.com"),
                    new Address("30 Choa Chu Kang Way"),
                    getGroupTagSet("KeatHong", "JC")),
            new Person(new Name("Nicole Hai Wei Ting"),
                    new Phone("83199487"),
                    new Email("nicolehaiweiting@gmail.com"),
                    new Address("20 Republic Avenue"),
                    getGroupTagSet("NicollHighway", "CCA")),
            new Person(new Name("Chun Ye"),
                    new Phone("83279894"),
                    new Email("chunye@gmail.com"),
                    new Address("825 Upper Thomson Road"),
                    getGroupTagSet("Springleaf", "Study")),
            new Person(new Name("Jing Kai Xiu"),
                    new Phone("83338543"),
                    new Email("jingkaixiu@gmail.com"),
                    new Address("1 Cashew Road"),
                    getGroupTagSet("Cashew", "TA")),
            new Person(new Name("Maxwell Neal"),
                    new Phone("83469406"),
                    new Email("maxwellneal@gmail.com"),
                    new Address("50 Neil Road"),
                    getGroupTagSet("Maxwell", "Study")),
            new Person(new Name("Shun Yi"),
                    new Phone("83716551"),
                    new Email("shunyi@gmail.com"),
                    new Address("301 Yishun Avenue 2"),
                    getGroupTagSet("Yishun", "NS")),
            new Person(new Name("Travis Scott"),
                    new Phone("83736092"),
                    new Email("travisscott@gmail.com"),
                    new Address("123456"),
                    getGroupTagSet("Tavistock")),
            new Person(new Name("Ang Mei Hua"),
                    new Phone("83804043"),
                    new Email("angmeihua@gmail.com"),
                    new Address("91 Ang Mo Kio Avenue 4"),
                    getGroupTagSet("Mayflower", "Study")),
            new Person(new Name("Teck Lee"),
                    new Phone("83828049"),
                    new Email("tecklee@gmail.com"),
                    new Address("101 Ponggol Seventeenth Avenue"),
                    getGroupTagSet("TeckLee")),
            new Person(new Name("Clark Kee"),
                    new Phone("83941948"),
                    new Email("clarkkee@gmail.com"),
                    new Address("10 Eu Tong Sen Street"),
                    getGroupTagSet("ClarkeQuay", "NUS")),
            new Person(new Name("Marina Wan"),
                    new Phone("83984732"),
                    new Email("marinawan@gmail.com"),
                    new Address("Marina One"),
                    getGroupTagSet("UpperThomson", "Enemy")),
            new Person(new Name("Ferra Park"),
                    new Phone("84239681"),
                    new Email("ferrapark@gmail.com"),
                    new Address("250 Race Course Road"),
                    getGroupTagSet("FarrerPark", "NUS")),
            new Person(new Name("Mary Meng"),
                    new Phone("84988118"),
                    new Email("marymeng@gmail.com"),
                    new Address("60 Marymount Road"),
                    getGroupTagSet("Marymount", "CCA")),
            new Person(new Name("Thomas Nakayama"),
                    new Phone("85020304"),
                    new Email("thomasnakayama@gmail.com"),
                    new Address("Zhongshan Mall"),
                    getGroupTagSet("UpperThomson", "Enemy")),
            new Person(new Name("Yunus Abdul Razak"),
                    new Phone("85070590"),
                    new Email("yunusabdulrazak@gmail.com"),
                    new Address("30 Eunos Crescent"),
                    getGroupTagSet("Eunos", "Groupmate")),
            new Person(new Name("Teck Whye"),
                    new Phone("85081157"),
                    new Email("teckwhye@gmail.com"),
                    new Address("10 Choa Chu Kang Way"),
                    getGroupTagSet("TeckWhye", "JC")),
            new Person(new Name("Edward Anson"),
                    new Phone("85142508"),
                    new Email("edwardanson@gmail.com"),
                    new Address("80 Shenton Way"),
                    getGroupTagSet("PrinceEdwardRoad", "CCA")),
            new Person(new Name("Dakota Windsor"),
                    new Phone("85225857"),
                    new Email("dakotawindsor@gmail.com"),
                    new Address("201 Old Airport Road"),
                    getGroupTagSet("Dakota", "CCA")),
            new Person(new Name("Jubilee Ang"),
                    new Phone("85240183"),
                    new Email("jubileeang@gmail.com"),
                    new Address("2450 Ang Mo Kio Avenue 8"),
                    getGroupTagSet("AngMoKio", "NS")),
            new Person(new Name("Dawson Quentin"),
                    new Phone("85319390"),
                    new Email("dawsonquentin@gmail.com"),
                    new Address("301 Commonwealth Avenue"),
                    getGroupTagSet("Queenstown", "Groupmate")),
            new Person(new Name("Gwon Se Rang"),
                    new Phone("85457476"),
                    new Email("gwonserang@gmail.com"),
                    new Address("600 Upper Serangoon Road"),
                    getGroupTagSet("Serangoon", "CCA", "NUS")),
            new Person(new Name("Sim Ga Rang"),
                    new Phone("85620815"),
                    new Email("simgarang@gmail.com"),
                    new Address("5 Sims Avenue"),
                    getGroupTagSet("Kallang", "Groupmate")),
            new Person(new Name("Yio Chu Kang"),
                    new Phone("85683494"),
                    new Email("yiochukang@gmail.com"),
                    new Address("3000 Ang Mo Kio Avenue 8"),
                    getGroupTagSet("YioChuKang", "NS")),
            new Person(new Name("Wisteria Chung"),
                    new Phone("85801897"),
                    new Email("wisteriachung@gmail.com"),
                    new Address("Wisteria Mall"),
                    getGroupTagSet("UpperThomson", "Enemy")),
            new Person(new Name("Mary Thomson"),
                    new Phone("86138754"),
                    new Email("marythomson@gmail.com"),
                    new Address("60 Marymount Road"),
                    getGroupTagSet("Marymount", "CCA")),
            new Person(new Name("Mary Caldecott"),
                    new Phone("86148572"),
                    new Email("marycaldecott@gmail.com"),
                    new Address("38 Toa Payoh Rise"),
                    getGroupTagSet("Caldecott", "CCA", "Study")),
            new Person(new Name("Alex Quentin"),
                    new Phone("86238115"),
                    new Email("alexquentin@gmail.com"),
                    new Address("301 Commonwealth Avenue"),
                    getGroupTagSet("Queenstown", "Groupmate")),
            new Person(new Name("Pearl Outram"),
                    new Phone("86470450"),
                    new Email("pearloutram@gmail.com"),
                    new Address("10 Outram Road"),
                    getGroupTagSet("OutramPark", "Groupmate", "NUS", "Study")),
            new Person(new Name("Nicholas Tan Bin"),
                    new Phone("86823655"),
                    new Email("nicholastanbin@gmail.com"),
                    new Address("20 Tampines Central 1"),
                    getGroupTagSet("Tampines", "TA", "Groupmate")),
            new Person(new Name("Tim Holland"),
                    new Phone("86864176"),
                    new Email("timholland@gmail.com"),
                    new Address("200 Holland Avenue"),
                    getGroupTagSet("HollandVillage", "CCA")),
            new Person(new Name("Syed Alwi Mustafa"),
                    new Phone("86966608"),
                    new Email("syedalwimustafa@gmail.com"),
                    new Address("Mustafa Centre"),
                    getGroupTagSet("UpperThomson", "Enemy")),
            new Person(new Name("Maxwell Smith"),
                    new Phone("87169803"),
                    new Email("maxwellsmith@gmail.com"),
                    new Address("50 Neil Road"),
                    getGroupTagSet("Maxwell", "Study")),
            new Person(new Name("Soo Teck"),
                    new Phone("87468381"),
                    new Email("sooteck@gmail.com"),
                    new Address("21 Punggol Way"),
                    getGroupTagSet("SooTeck")),
            new Person(new Name("Scott Newton"),
                    new Phone("87548202"),
                    new Email("scottnewton@gmail.com"),
                    new Address("49 Scotts Road"),
                    getGroupTagSet("Newton", "TA", "NS")),
            new Person(new Name("Shannon Wei"),
                    new Phone("87689276"),
                    new Email("shannonwei@gmail.com"),
                    new Address("2 Park Street"),
                    getGroupTagSet("ShentonWay", "Study")),
            new Person(new Name("Glenn Napier"),
                    new Phone("88308087"),
                    new Email("glennnapier@gmail.com"),
                    new Address("2 Napier Road"),
                    getGroupTagSet("Napier", "Study")),
            new Person(new Name("Wen Qing"),
                    new Phone("88324728"),
                    new Email("wenqing@gmail.com"),
                    new Address("900 Serangoon Road"),
                    getGroupTagSet("BoonKeng", "NUS")),
            new Person(new Name("Choa Chu Kang"),
                    new Phone("88614241"),
                    new Email("choachukang@gmail.com"),
                    new Address("10 Choa Chu Kang Avenue 4"),
                    getGroupTagSet("ChoaChuKang", "JC", "JC", "NS")),
            new Person(new Name("Kevin Ho"),
                    new Phone("88616600"),
                    new Email("kevinho@gmail.com"),
                    new Address("900 Upper Serangoon Road"),
                    getGroupTagSet("Kovan", "NUS")),
            new Person(new Name("Hong Shan"),
                    new Phone("88998690"),
                    new Email("hongshan@gmail.com"),
                    new Address("920 Tiong Bahru Road"),
                    getGroupTagSet("Redhill", "Groupmate")),
            new Person(new Name("Bart Lee"),
                    new Phone("89123662"),
                    new Email("bartlee@gmail.com"),
                    new Address("90 Bartley Road"),
                    getGroupTagSet("Bartley", "CCA")),
            new Person(new Name("Marcy Ling"),
                    new Phone("89453423"),
                    new Email("marcyling@gmail.com"),
                    new Address("71 Woodlands Avenue 3"),
                    getGroupTagSet("Marsiling", "NS")),
            new Person(new Name("Tan Kah Kee"),
                    new Phone("89687340"),
                    new Email("tankahkee@gmail.com"),
                    new Address("651 Bukit Timah Road"),
                    getGroupTagSet("TanKahKee", "TA")),
            new Person(new Name("Benjamin Coolen"),
                    new Phone("89704326"),
                    new Email("benjamincoolen@gmail.com"),
                    new Address("31 Bencoolen Street"),
                    getGroupTagSet("Bencoolen", "TA")),
            new Person(new Name("Albert Park"),
                    new Phone("89721323"),
                    new Email("albertpark@gmail.com"),
                    new Address("2 Blackmore Drive"),
                    getGroupTagSet("KingAlbertPark", "TA")),
            new Person(new Name("Clement Tee"),
                    new Phone("89734335"),
                    new Email("clementtee@gmail.com"),
                    new Address("3150 Commonwealth Avenue West"),
                    getGroupTagSet("Clementi", "Groupmate")),
            new Person(new Name("Brad Toh"),
                    new Phone("89766812"),
                    new Email("bradtoh@gmail.com"),
                    new Address("377 Lorong 1 Toa Payoh"),
                    getGroupTagSet("Braddell", "NS")),
            new Person(new Name("Komyo San"),
                    new Phone("89974859"),
                    new Email("komyosan@gmail.com"),
                    new Address("100 Sin Ming Avenue"),
                    getGroupTagSet("BrightHill", "Study")),
            new Person(new Name("Sam Kee"),
                    new Phone("91136967"),
                    new Email("samkee@gmail.com"),
                    new Address("10 Sentul Crescent"),
                    getGroupTagSet("SamKee")),
            new Person(new Name("Nee Soon"),
                    new Phone("91172349"),
                    new Email("neesoon@gmail.com"),
                    new Address("301 Yishun Avenue 2"),
                    getGroupTagSet("Yishun", "NS")),
            new Person(new Name("Boon Lay"),
                    new Phone("91414526"),
                    new Email("boonlay@gmail.com"),
                    new Address("301 Boon Lay Way"),
                    getGroupTagSet("BoonLay", "Groupmate", "JC")),
            new Person(new Name("Juan Fullerton"),
                    new Phone("91539072"),
                    new Email("juanfullerton@gmail.com"),
                    new Address("One Fullerton"),
                    getGroupTagSet("UpperThomson", "Enemy")),
            new Person(new Name("Leedon Holland"),
                    new Phone("91601808"),
                    new Email("leedonholland@gmail.com"),
                    new Address("200 Holland Avenue"),
                    getGroupTagSet("HollandVillage", "CCA")),
            new Person(new Name("Vernon Lee"),
                    new Phone("91727471"),
                    new Email("vernonlee@gmail.com"),
                    new Address("90 Bartley Road"),
                    getGroupTagSet("Bartley", "CCA")),
            new Person(new Name("Edward Richards"),
                    new Phone("91893538"),
                    new Email("edwardrichards@gmail.com"),
                    new Address("301 South Buona Vista Road"),
                    getGroupTagSet("KentRidge", "CCA")),
            new Person(new Name("Kent Richards"),
                    new Phone("91898299"),
                    new Email("kentrichards@gmail.com"),
                    new Address("301 South Buona Vista Road"),
                    getGroupTagSet("KentRidge", "CCA")),
            new Person(new Name("Khadijah Al Junied"),
                    new Phone("92110759"),
                    new Email("khadijahaljunied@gmail.com"),
                    new Address("81 Lorong 25 Geylang"),
                    getGroupTagSet("Aljunied", "Groupmate")),
            new Person(new Name("Ritchie Thomson"),
                    new Phone("92517840"),
                    new Email("ritchiethomson@gmail.com"),
                    new Address("1 Jalan Keli"),
                    getGroupTagSet("UpperThomson", "Study")),
            new Person(new Name("Amirah Tan"),
                    new Phone("92759497"),
                    new Email("amirahtan@gmail.com"),
                    new Address("920 New Upper Changi Road"),
                    getGroupTagSet("TanahMerah", "Groupmate")),
            new Person(new Name("Charles Windsor"),
                    new Phone("92821042"),
                    new Email("charleswindsor@gmail.com"),
                    new Address("301 Mountbatten Road"),
                    getGroupTagSet("Mountbatten", "CCA")),
            new Person(new Name("Ang Djit Sun"),
                    new Phone("92844320"),
                    new Email("angdjitsun@gmail.com"),
                    new Address("2450 Ang Mo Kio Avenue 8"),
                    getGroupTagSet("AngMoKio", "NS")),
            new Person(new Name("Maya Takashi"),
                    new Phone("92870632"),
                    new Email("mayatakashi@gmail.com"),
                    new Address("Ngee Ann City"),
                    getGroupTagSet("UpperThomson", "Enemy")),
            new Person(new Name("Low Wong Chuan"),
                    new Phone("93171134"),
                    new Email("lowwongchuan@gmail.com"),
                    new Address("150 Serangoon Avenue 3"),
                    getGroupTagSet("LorongChuan", "CCA")),
            new Person(new Name("Robin Stevens"),
                    new Phone("93232695"),
                    new Email("robinstevens@gmail.com"),
                    new Address("92 Stevens Road"),
                    getGroupTagSet("Stevens", "TA", "Study")),
            new Person(new Name("Wen Li"),
                    new Phone("93242433"),
                    new Email("wenli@gmail.com"),
                    new Address("301 Boon Lay Way"),
                    getGroupTagSet("BoonLay", "Groupmate", "JC")),
            new Person(new Name("Amirah Tee"),
                    new Phone("93550268"),
                    new Email("amirahtee@gmail.com"),
                    new Address("70 Woodlands Avenue 7"),
                    getGroupTagSet("Admiralty", "NS")),
            new Person(new Name("Albert Blackmore"),
                    new Phone("93798357"),
                    new Email("albertblackmore@gmail.com"),
                    new Address("2 Blackmore Drive"),
                    getGroupTagSet("KingAlbertPark", "TA")),
            new Person(new Name("Illyas Alhaq"),
                    new Phone("93880541"),
                    new Email("illyasalhaq@gmail.com"),
                    new Address("Elias Mall"),
                    getGroupTagSet("UpperThomson", "Enemy")),
            new Person(new Name("Marina Bay"),
                    new Phone("93905945"),
                    new Email("marinabay@gmail.com"),
                    new Address("21 Park Street"),
                    getGroupTagSet("MarinaBay", "NS", "Study")),
            new Person(new Name("Victoria Raffles"),
                    new Phone("94074112"),
                    new Email("victoriaraffles@gmail.com"),
                    new Address("5 Raffles Place"),
                    getGroupTagSet("RafflesPlace", "Groupmate", "NS")),
            new Person(new Name("Benjamin DeMeer"),
                    new Phone("94663556"),
                    new Email("benjamindemeer@gmail.com"),
                    new Address("11 Kallang Bahru"),
                    getGroupTagSet("Bendemeer", "TA")),
            new Person(new Name("Cheng Lim"),
                    new Phone("94740430"),
                    new Email("chenglim@gmail.com"),
                    new Address("5 Anchorvale Street"),
                    getGroupTagSet("ChengLim")),
            new Person(new Name("Seth Summers"),
                    new Phone("94914166"),
                    new Email("sethsummers@gmail.com"),
                    new Address("1 Somerset Road"),
                    getGroupTagSet("Somerset", "NS")),
            new Person(new Name("Ang Mo Kio"),
                    new Phone("95514560"),
                    new Email("angmokio@gmail.com"),
                    new Address("2450 Ang Mo Kio Avenue 8"),
                    getGroupTagSet("AngMoKio", "NS")),
            new Person(new Name("Khoo Pang"),
                    new Phone("96001426"),
                    new Email("khoopang@gmail.com"),
                    new Address("60 Fernvale Street"),
                    getGroupTagSet("Kupang")),
            new Person(new Name("May See"),
                    new Phone("96343944"),
                    new Email("maysee@gmail.com"),
                    new Address("30 Simei Street 3"),
                    getGroupTagSet("Simei", "Groupmate")),
            new Person(new Name("Ewan MacPherson"),
                    new Phone("96381267"),
                    new Email("ewanmacpherson@gmail.com"),
                    new Address("171 Paya Lebar Road"),
                    getGroupTagSet("MacPherson", "CCA", "TA")),
            new Person(new Name("Zhang Yi"),
                    new Phone("96727706"),
                    new Email("zhangyi@gmail.com"),
                    new Address("Changi Airport"),
                    getGroupTagSet("UpperThomson", "Enemy")),
            new Person(new Name("Bee Shan"),
                    new Phone("96731695"),
                    new Email("beeshan@gmail.com"),
                    new Address("200 Bishan Road"),
                    getGroupTagSet("Bishan", "CCA", "NS")),
            new Person(new Name("Melania Walker"),
                    new Phone("96745111"),
                    new Email("melaniawalker@gmail.com"),
                    new Address("Millenia Walk"),
                    getGroupTagSet("UpperThomson", "Enemy")),
            new Person(new Name("Dong Yu Lang"),
                    new Phone("96784387"),
                    new Email("dongyulang@gmail.com"),
                    new Address("10 Jurong East Street 12"),
                    getGroupTagSet("JurongEast", "NS")),
            new Person(new Name("Ford Canning"),
                    new Phone("96791630"),
                    new Email("fordcanning@gmail.com"),
                    new Address("170 River Valley Road"),
                    getGroupTagSet("FortCanning", "TA")),
            new Person(new Name("Nurul Khatibah Abdul Ibrahim"),
                    new Phone("96813624"),
                    new Email("nurulkhatibahabdulibrahim@gmail.com"),
                    new Address("201 Yishun Avenue 2"),
                    getGroupTagSet("Khatib", "NS")),
            new Person(new Name("Steven Tan"),
                    new Phone("97186977"),
                    new Email("steventan@gmail.com"),
                    new Address("92 Stevens Road"),
                    getGroupTagSet("Stevens", "TA", "Study")),
            new Person(new Name("Sallim Mattar"),
                    new Phone("97314652"),
                    new Email("sallimmattar@gmail.com"),
                    new Address("60 Merpati Road"),
                    getGroupTagSet("Mattar", "TA")),
            new Person(new Name("Nicole Windsor"),
                    new Phone("97485163"),
                    new Email("nicolewindsor@gmail.com"),
                    new Address("20 Republic Avenue"),
                    getGroupTagSet("NicollHighway", "CCA")),
            new Person(new Name("Novena Thomson"),
                    new Phone("97552563"),
                    new Email("novenathomson@gmail.com"),
                    new Address("250 Thomson Road"),
                    getGroupTagSet("Novena", "NS")),
            new Person(new Name("George Richards"),
                    new Phone("97560397"),
                    new Email("georgerichards@gmail.com"),
                    new Address("301 South Buona Vista Road"),
                    getGroupTagSet("KentRidge", "CCA")),
            new Person(new Name("Steven Whitley"),
                    new Phone("97651500"),
                    new Email("stevenwhitley@gmail.com"),
                    new Address("92 Stevens Road"),
                    getGroupTagSet("Stevens", "TA", "Study")),
            new Person(new Name("Eusoff Richards"),
                    new Phone("98138349"),
                    new Email("eusoffrichards@gmail.com"),
                    new Address("301 South Buona Vista Road"),
                    getGroupTagSet("KentRidge", "CCA")),
            new Person(new Name("Joo Rong"),
                    new Phone("98432890"),
                    new Email("joorong@gmail.com"),
                    new Address("10 Jurong East Street 12"),
                    getGroupTagSet("JurongEast", "NS")),
            new Person(new Name("Granger Summers"),
                    new Phone("99135499"),
                    new Email("grangersummers@gmail.com"),
                    new Address("1 Somerset Road"),
                    getGroupTagSet("Somerset", "NS")),
            new Person(new Name("Yew Tee"),
                    new Phone("99278628"),
                    new Email("yewtee@gmail.com"),
                    new Address("61 Choa Chu Kang Drive"),
                    getGroupTagSet("YewTee", "NS")),
            new Person(new Name("Soon Teck"),
                    new Phone("99340280"),
                    new Email("soonteck@gmail.com"),
                    new Address("Suntec City"),
                    getGroupTagSet("UpperThomson", "Enemy")),
            new Person(new Name("Wang Kok"),
                    new Phone("99741972"),
                    new Email("wangkok@gmail.com"),
                    new Address("10 Sengkang Central"),
                    getGroupTagSet("Buangkok", "NUS")),
            new Person(new Name("Boon Kheng"),
                    new Phone("99812385"),
                    new Email("boonkheng@gmail.com"),
                    new Address("900 Serangoon Road"),
                    getGroupTagSet("BoonKeng", "NUS"))
        };
    }

    public static ReadOnlyEduMate getSampleEduMate() {
        EduMate sampleAb = new EduMate();
        for (Person samplePerson : getSamplePersons()) {
            sampleAb.addPerson(samplePerson);
        }
        sampleAb.setUser(getSampleUser());
        return sampleAb;
    }

    /**
     * Returns a tag set containing the list of strings given.
     */
    public static Set<GroupTag> getGroupTagSet(String... strings) {
        return Arrays.stream(strings)
                .map(GroupTag::new)
                .collect(Collectors.toSet());
    }

}
